// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_d92b_csc_0_v_csc_core_Pipeline_VITIS_LOOP_91_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        stream_in_hresampled_dout,
        stream_in_hresampled_num_data_valid,
        stream_in_hresampled_fifo_cap,
        stream_in_hresampled_empty_n,
        stream_in_hresampled_read,
        stream_csc_din,
        stream_csc_num_data_valid,
        stream_csc_fifo_cap,
        stream_csc_full_n,
        stream_csc_write,
        add_ln89,
        offsetR,
        K11_load_cast,
        K12_load_cast,
        K13_load_cast,
        offsetG,
        K21_load_cast,
        K22_load_cast,
        K23_load_cast,
        offsetB,
        K31_load_cast,
        K32_load_cast,
        K33_load_cast,
        zext_ln89_1,
        zext_ln89,
        ClipMax_read,
        ClampMin_read
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [29:0] stream_in_hresampled_dout;
input  [4:0] stream_in_hresampled_num_data_valid;
input  [4:0] stream_in_hresampled_fifo_cap;
input   stream_in_hresampled_empty_n;
output   stream_in_hresampled_read;
output  [29:0] stream_csc_din;
input  [4:0] stream_csc_num_data_valid;
input  [4:0] stream_csc_fifo_cap;
input   stream_csc_full_n;
output   stream_csc_write;
input  [13:0] add_ln89;
input  [23:0] offsetR;
input  [15:0] K11_load_cast;
input  [15:0] K12_load_cast;
input  [15:0] K13_load_cast;
input  [23:0] offsetG;
input  [15:0] K21_load_cast;
input  [15:0] K22_load_cast;
input  [15:0] K23_load_cast;
input  [23:0] offsetB;
input  [15:0] K31_load_cast;
input  [15:0] K32_load_cast;
input  [15:0] K33_load_cast;
input  [9:0] zext_ln89_1;
input  [9:0] zext_ln89;
input  [9:0] ClipMax_read;
input  [9:0] ClampMin_read;

reg ap_idle;
reg stream_in_hresampled_read;
reg stream_csc_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln91_fu_271_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    stream_in_hresampled_blk_n;
wire    ap_block_pp0_stage0;
reg    stream_csc_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [15:0] zext_ln89_cast_fu_219_p1;
reg   [15:0] zext_ln89_cast_reg_696;
wire   [15:0] zext_ln89_1_cast_fu_223_p1;
reg   [15:0] zext_ln89_1_cast_reg_703;
wire  signed [25:0] K33_load_cast_cast_fu_227_p1;
reg  signed [25:0] K33_load_cast_cast_reg_710;
wire  signed [25:0] K32_load_cast_cast_fu_231_p1;
reg  signed [25:0] K32_load_cast_cast_reg_715;
wire  signed [25:0] K31_load_cast_cast_fu_235_p1;
reg  signed [25:0] K31_load_cast_cast_reg_720;
wire  signed [25:0] K23_load_cast_cast_fu_239_p1;
reg  signed [25:0] K23_load_cast_cast_reg_725;
wire  signed [25:0] K22_load_cast_cast_fu_243_p1;
reg  signed [25:0] K22_load_cast_cast_reg_730;
wire  signed [25:0] K21_load_cast_cast_fu_247_p1;
reg  signed [25:0] K21_load_cast_cast_reg_735;
wire  signed [25:0] K13_load_cast_cast_fu_251_p1;
reg  signed [25:0] K13_load_cast_cast_reg_740;
wire  signed [25:0] K12_load_cast_cast_fu_255_p1;
reg  signed [25:0] K12_load_cast_cast_reg_745;
wire  signed [25:0] K11_load_cast_cast_fu_259_p1;
reg  signed [25:0] K11_load_cast_cast_reg_750;
reg   [9:0] Gpix_reg_759;
reg   [9:0] Gpix_reg_759_pp0_iter2_reg;
wire   [25:0] zext_ln61_fu_302_p1;
reg   [9:0] trunc_ln_reg_771;
reg   [9:0] trunc_ln_reg_771_pp0_iter2_reg;
wire  signed [25:0] mul_ln147_1_fu_331_p2;
reg  signed [25:0] mul_ln147_1_reg_781;
wire  signed [25:0] mul_ln147_2_fu_336_p2;
reg  signed [25:0] mul_ln147_2_reg_787;
wire  signed [25:0] mul_ln149_1_fu_350_p2;
reg  signed [25:0] mul_ln149_1_reg_798;
wire  signed [25:0] mul_ln149_2_fu_355_p2;
reg  signed [25:0] mul_ln149_2_reg_804;
wire  signed [25:0] mul_ln151_1_fu_369_p2;
reg  signed [25:0] mul_ln151_1_reg_815;
wire  signed [25:0] mul_ln151_2_fu_374_p2;
reg  signed [25:0] mul_ln151_2_reg_821;
wire   [21:0] trunc_ln147_fu_385_p1;
reg   [21:0] trunc_ln147_reg_827;
wire   [21:0] trunc_ln147_1_fu_401_p1;
reg   [21:0] trunc_ln147_1_reg_832;
reg   [15:0] Rres_reg_837;
wire   [21:0] trunc_ln149_fu_431_p1;
reg   [21:0] trunc_ln149_reg_843;
wire   [21:0] trunc_ln149_1_fu_447_p1;
reg   [21:0] trunc_ln149_1_reg_848;
reg   [15:0] Gres_reg_853;
wire   [21:0] trunc_ln151_fu_477_p1;
reg   [21:0] trunc_ln151_reg_859;
wire   [21:0] trunc_ln151_1_fu_493_p1;
reg   [21:0] trunc_ln151_1_reg_864;
reg   [15:0] Bres_reg_869;
wire   [9:0] select_ln153_1_fu_554_p3;
reg   [9:0] select_ln153_1_reg_875;
wire   [9:0] select_ln155_1_fu_604_p3;
reg   [9:0] select_ln155_1_reg_880;
wire   [9:0] select_ln154_1_fu_618_p3;
reg   [9:0] select_ln154_1_reg_885;
reg   [13:0] x_fu_100;
wire   [13:0] x_4_fu_277_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_x_3;
reg    ap_block_pp0_stage0_01001;
wire   [9:0] Rpix_fu_288_p1;
wire  signed [23:0] or_ln147_fu_322_p2;
wire   [9:0] mul_ln147_1_fu_331_p0;
wire   [25:0] zext_ln61_1_fu_316_p1;
wire  signed [15:0] mul_ln147_1_fu_331_p1;
wire  signed [15:0] mul_ln147_2_fu_336_p0;
wire   [9:0] mul_ln147_2_fu_336_p1;
wire   [25:0] zext_ln61_2_fu_319_p1;
wire  signed [23:0] or_ln149_fu_341_p2;
wire   [9:0] mul_ln149_1_fu_350_p0;
wire  signed [15:0] mul_ln149_1_fu_350_p1;
wire  signed [15:0] mul_ln149_2_fu_355_p0;
wire   [9:0] mul_ln149_2_fu_355_p1;
wire  signed [23:0] or_ln151_fu_360_p2;
wire   [9:0] mul_ln151_1_fu_369_p0;
wire  signed [15:0] mul_ln151_1_fu_369_p1;
wire  signed [15:0] mul_ln151_2_fu_374_p0;
wire   [9:0] mul_ln151_2_fu_374_p1;
wire  signed [26:0] grp_fu_633_p3;
wire  signed [26:0] sext_ln147_2_fu_379_p1;
wire  signed [26:0] sext_ln147_3_fu_382_p1;
wire   [25:0] add_ln147_4_fu_391_p2;
wire   [26:0] add_ln147_1_fu_395_p2;
wire  signed [27:0] sext_ln147_5_fu_405_p1;
wire  signed [27:0] sext_ln147_4_fu_388_p1;
wire   [27:0] add_ln147_2_fu_409_p2;
wire  signed [26:0] grp_fu_642_p3;
wire  signed [26:0] sext_ln149_2_fu_425_p1;
wire  signed [26:0] sext_ln149_3_fu_428_p1;
wire   [25:0] add_ln149_4_fu_437_p2;
wire   [26:0] add_ln149_1_fu_441_p2;
wire  signed [27:0] sext_ln149_5_fu_451_p1;
wire  signed [27:0] sext_ln149_4_fu_434_p1;
wire   [27:0] add_ln149_2_fu_455_p2;
wire  signed [26:0] grp_fu_651_p3;
wire  signed [26:0] sext_ln151_2_fu_471_p1;
wire  signed [26:0] sext_ln151_3_fu_474_p1;
wire   [25:0] add_ln151_4_fu_483_p2;
wire   [26:0] add_ln151_1_fu_487_p2;
wire  signed [27:0] sext_ln151_5_fu_497_p1;
wire  signed [27:0] sext_ln151_4_fu_480_p1;
wire   [27:0] add_ln151_2_fu_501_p2;
wire   [21:0] add_ln147_3_fu_517_p2;
wire   [0:0] icmp_ln153_1_fu_533_p2;
wire   [9:0] trunc_ln4_fu_537_p4;
wire   [0:0] icmp_ln153_fu_529_p2;
wire   [9:0] select_ln153_fu_547_p3;
wire   [21:0] add_ln149_3_fu_521_p2;
wire   [21:0] add_ln151_3_fu_525_p2;
wire   [0:0] icmp_ln155_1_fu_583_p2;
wire   [9:0] trunc_ln6_fu_587_p4;
wire   [0:0] icmp_ln155_fu_579_p2;
wire   [9:0] select_ln155_fu_597_p3;
wire   [0:0] icmp_ln154_1_fu_565_p2;
wire   [9:0] trunc_ln5_fu_569_p4;
wire   [0:0] icmp_ln154_fu_561_p2;
wire   [9:0] select_ln154_fu_611_p3;
wire  signed [15:0] grp_fu_633_p0;
wire   [9:0] grp_fu_633_p1;
wire  signed [15:0] grp_fu_642_p0;
wire   [9:0] grp_fu_642_p1;
wire  signed [15:0] grp_fu_651_p0;
wire   [9:0] grp_fu_651_p1;
reg    grp_fu_633_ce;
reg    grp_fu_642_ce;
reg    grp_fu_651_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_done_reg = 1'b0;
end

bd_d92b_csc_0_mul_10ns_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_10ns_16s_26_1_1_U134(
    .din0(mul_ln147_1_fu_331_p0),
    .din1(mul_ln147_1_fu_331_p1),
    .dout(mul_ln147_1_fu_331_p2)
);

bd_d92b_csc_0_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U135(
    .din0(mul_ln147_2_fu_336_p0),
    .din1(mul_ln147_2_fu_336_p1),
    .dout(mul_ln147_2_fu_336_p2)
);

bd_d92b_csc_0_mul_10ns_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_10ns_16s_26_1_1_U136(
    .din0(mul_ln149_1_fu_350_p0),
    .din1(mul_ln149_1_fu_350_p1),
    .dout(mul_ln149_1_fu_350_p2)
);

bd_d92b_csc_0_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U137(
    .din0(mul_ln149_2_fu_355_p0),
    .din1(mul_ln149_2_fu_355_p1),
    .dout(mul_ln149_2_fu_355_p2)
);

bd_d92b_csc_0_mul_10ns_16s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 26 ))
mul_10ns_16s_26_1_1_U138(
    .din0(mul_ln151_1_fu_369_p0),
    .din1(mul_ln151_1_fu_369_p1),
    .dout(mul_ln151_1_fu_369_p2)
);

bd_d92b_csc_0_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U139(
    .din0(mul_ln151_2_fu_374_p0),
    .din1(mul_ln151_2_fu_374_p1),
    .dout(mul_ln151_2_fu_374_p2)
);

bd_d92b_csc_0_mac_muladd_16s_10ns_24s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_10ns_24s_27_4_1_U140(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_633_p0),
    .din1(grp_fu_633_p1),
    .din2(or_ln147_fu_322_p2),
    .ce(grp_fu_633_ce),
    .dout(grp_fu_633_p3)
);

bd_d92b_csc_0_mac_muladd_16s_10ns_24s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_10ns_24s_27_4_1_U141(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_642_p0),
    .din1(grp_fu_642_p1),
    .din2(or_ln149_fu_341_p2),
    .ce(grp_fu_642_ce),
    .dout(grp_fu_642_p3)
);

bd_d92b_csc_0_mac_muladd_16s_10ns_24s_27_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 27 ))
mac_muladd_16s_10ns_24s_27_4_1_U142(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_651_p0),
    .din1(grp_fu_651_p1),
    .din2(or_ln151_fu_360_p2),
    .ce(grp_fu_651_ce),
    .dout(grp_fu_651_p3)
);

bd_d92b_csc_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln91_fu_271_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_100 <= x_4_fu_277_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_100 <= 14'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Bres_reg_869 <= {{add_ln151_2_fu_501_p2[27:12]}};
        Gpix_reg_759_pp0_iter2_reg <= Gpix_reg_759;
        Gres_reg_853 <= {{add_ln149_2_fu_455_p2[27:12]}};
        Rres_reg_837 <= {{add_ln147_2_fu_409_p2[27:12]}};
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        mul_ln147_1_reg_781 <= mul_ln147_1_fu_331_p2;
        mul_ln147_2_reg_787 <= mul_ln147_2_fu_336_p2;
        mul_ln149_1_reg_798 <= mul_ln149_1_fu_350_p2;
        mul_ln149_2_reg_804 <= mul_ln149_2_fu_355_p2;
        mul_ln151_1_reg_815 <= mul_ln151_1_fu_369_p2;
        mul_ln151_2_reg_821 <= mul_ln151_2_fu_374_p2;
        select_ln153_1_reg_875 <= select_ln153_1_fu_554_p3;
        select_ln154_1_reg_885 <= select_ln154_1_fu_618_p3;
        select_ln155_1_reg_880 <= select_ln155_1_fu_604_p3;
        trunc_ln147_1_reg_832 <= trunc_ln147_1_fu_401_p1;
        trunc_ln147_reg_827 <= trunc_ln147_fu_385_p1;
        trunc_ln149_1_reg_848 <= trunc_ln149_1_fu_447_p1;
        trunc_ln149_reg_843 <= trunc_ln149_fu_431_p1;
        trunc_ln151_1_reg_864 <= trunc_ln151_1_fu_493_p1;
        trunc_ln151_reg_859 <= trunc_ln151_fu_477_p1;
        trunc_ln_reg_771_pp0_iter2_reg <= trunc_ln_reg_771;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Gpix_reg_759 <= {{stream_in_hresampled_dout[19:10]}};
        K11_load_cast_cast_reg_750 <= K11_load_cast_cast_fu_259_p1;
        K12_load_cast_cast_reg_745 <= K12_load_cast_cast_fu_255_p1;
        K13_load_cast_cast_reg_740 <= K13_load_cast_cast_fu_251_p1;
        K21_load_cast_cast_reg_735 <= K21_load_cast_cast_fu_247_p1;
        K22_load_cast_cast_reg_730 <= K22_load_cast_cast_fu_243_p1;
        K23_load_cast_cast_reg_725 <= K23_load_cast_cast_fu_239_p1;
        K31_load_cast_cast_reg_720 <= K31_load_cast_cast_fu_235_p1;
        K32_load_cast_cast_reg_715 <= K32_load_cast_cast_fu_231_p1;
        K33_load_cast_cast_reg_710 <= K33_load_cast_cast_fu_227_p1;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln_reg_771 <= {{stream_in_hresampled_dout[29:20]}};
        zext_ln89_1_cast_reg_703[9 : 0] <= zext_ln89_1_cast_fu_223_p1[9 : 0];
        zext_ln89_cast_reg_696[9 : 0] <= zext_ln89_cast_fu_219_p1[9 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln91_fu_271_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter5_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_3 = 14'd1;
    end else begin
        ap_sig_allocacmp_x_3 = x_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_633_ce = 1'b1;
    end else begin
        grp_fu_633_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_642_ce = 1'b1;
    end else begin
        grp_fu_642_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_651_ce = 1'b1;
    end else begin
        grp_fu_651_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        stream_csc_blk_n = stream_csc_full_n;
    end else begin
        stream_csc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        stream_csc_write = 1'b1;
    end else begin
        stream_csc_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_hresampled_blk_n = stream_in_hresampled_empty_n;
    end else begin
        stream_in_hresampled_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        stream_in_hresampled_read = 1'b1;
    end else begin
        stream_in_hresampled_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign K11_load_cast_cast_fu_259_p1 = $signed(K11_load_cast);

assign K12_load_cast_cast_fu_255_p1 = $signed(K12_load_cast);

assign K13_load_cast_cast_fu_251_p1 = $signed(K13_load_cast);

assign K21_load_cast_cast_fu_247_p1 = $signed(K21_load_cast);

assign K22_load_cast_cast_fu_243_p1 = $signed(K22_load_cast);

assign K23_load_cast_cast_fu_239_p1 = $signed(K23_load_cast);

assign K31_load_cast_cast_fu_235_p1 = $signed(K31_load_cast);

assign K32_load_cast_cast_fu_231_p1 = $signed(K32_load_cast);

assign K33_load_cast_cast_fu_227_p1 = $signed(K33_load_cast);

assign Rpix_fu_288_p1 = stream_in_hresampled_dout[9:0];

assign add_ln147_1_fu_395_p2 = ($signed(sext_ln147_2_fu_379_p1) + $signed(sext_ln147_3_fu_382_p1));

assign add_ln147_2_fu_409_p2 = ($signed(sext_ln147_5_fu_405_p1) + $signed(sext_ln147_4_fu_388_p1));

assign add_ln147_3_fu_517_p2 = (trunc_ln147_1_reg_832 + trunc_ln147_reg_827);

assign add_ln147_4_fu_391_p2 = ($signed(mul_ln147_1_reg_781) + $signed(mul_ln147_2_reg_787));

assign add_ln149_1_fu_441_p2 = ($signed(sext_ln149_2_fu_425_p1) + $signed(sext_ln149_3_fu_428_p1));

assign add_ln149_2_fu_455_p2 = ($signed(sext_ln149_5_fu_451_p1) + $signed(sext_ln149_4_fu_434_p1));

assign add_ln149_3_fu_521_p2 = (trunc_ln149_1_reg_848 + trunc_ln149_reg_843);

assign add_ln149_4_fu_437_p2 = ($signed(mul_ln149_1_reg_798) + $signed(mul_ln149_2_reg_804));

assign add_ln151_1_fu_487_p2 = ($signed(sext_ln151_2_fu_471_p1) + $signed(sext_ln151_3_fu_474_p1));

assign add_ln151_2_fu_501_p2 = ($signed(sext_ln151_5_fu_497_p1) + $signed(sext_ln151_4_fu_480_p1));

assign add_ln151_3_fu_525_p2 = (trunc_ln151_1_reg_864 + trunc_ln151_reg_859);

assign add_ln151_4_fu_483_p2 = ($signed(mul_ln151_1_reg_815) + $signed(mul_ln151_2_reg_821));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((stream_csc_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((stream_in_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((stream_csc_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((stream_in_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((stream_csc_full_n == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1)) | ((stream_in_hresampled_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (stream_in_hresampled_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter6 = (stream_csc_full_n == 1'b0);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign grp_fu_633_p0 = K11_load_cast_cast_reg_750;

assign grp_fu_633_p1 = zext_ln61_fu_302_p1;

assign grp_fu_642_p0 = K21_load_cast_cast_reg_735;

assign grp_fu_642_p1 = zext_ln61_fu_302_p1;

assign grp_fu_651_p0 = K31_load_cast_cast_reg_720;

assign grp_fu_651_p1 = zext_ln61_fu_302_p1;

assign icmp_ln153_1_fu_533_p2 = (($signed(Rres_reg_837) > $signed(zext_ln89_cast_reg_696)) ? 1'b1 : 1'b0);

assign icmp_ln153_fu_529_p2 = (($signed(Rres_reg_837) < $signed(zext_ln89_1_cast_reg_703)) ? 1'b1 : 1'b0);

assign icmp_ln154_1_fu_565_p2 = (($signed(Gres_reg_853) > $signed(zext_ln89_cast_reg_696)) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_561_p2 = (($signed(Gres_reg_853) < $signed(zext_ln89_1_cast_reg_703)) ? 1'b1 : 1'b0);

assign icmp_ln155_1_fu_583_p2 = (($signed(Bres_reg_869) > $signed(zext_ln89_cast_reg_696)) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_579_p2 = (($signed(Bres_reg_869) < $signed(zext_ln89_1_cast_reg_703)) ? 1'b1 : 1'b0);

assign icmp_ln91_fu_271_p2 = ((ap_sig_allocacmp_x_3 == add_ln89) ? 1'b1 : 1'b0);

assign mul_ln147_1_fu_331_p0 = zext_ln61_1_fu_316_p1;

assign mul_ln147_1_fu_331_p1 = K12_load_cast_cast_reg_745;

assign mul_ln147_2_fu_336_p0 = K13_load_cast_cast_reg_740;

assign mul_ln147_2_fu_336_p1 = zext_ln61_2_fu_319_p1;

assign mul_ln149_1_fu_350_p0 = zext_ln61_1_fu_316_p1;

assign mul_ln149_1_fu_350_p1 = K22_load_cast_cast_reg_730;

assign mul_ln149_2_fu_355_p0 = K23_load_cast_cast_reg_725;

assign mul_ln149_2_fu_355_p1 = zext_ln61_2_fu_319_p1;

assign mul_ln151_1_fu_369_p0 = zext_ln61_1_fu_316_p1;

assign mul_ln151_1_fu_369_p1 = K32_load_cast_cast_reg_715;

assign mul_ln151_2_fu_374_p0 = K33_load_cast_cast_reg_710;

assign mul_ln151_2_fu_374_p1 = zext_ln61_2_fu_319_p1;

assign or_ln147_fu_322_p2 = (offsetR | 24'd2048);

assign or_ln149_fu_341_p2 = (offsetG | 24'd2048);

assign or_ln151_fu_360_p2 = (offsetB | 24'd2048);

assign select_ln153_1_fu_554_p3 = ((icmp_ln153_fu_529_p2[0:0] == 1'b1) ? ClampMin_read : select_ln153_fu_547_p3);

assign select_ln153_fu_547_p3 = ((icmp_ln153_1_fu_533_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln4_fu_537_p4);

assign select_ln154_1_fu_618_p3 = ((icmp_ln154_fu_561_p2[0:0] == 1'b1) ? ClampMin_read : select_ln154_fu_611_p3);

assign select_ln154_fu_611_p3 = ((icmp_ln154_1_fu_565_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln5_fu_569_p4);

assign select_ln155_1_fu_604_p3 = ((icmp_ln155_fu_579_p2[0:0] == 1'b1) ? ClampMin_read : select_ln155_fu_597_p3);

assign select_ln155_fu_597_p3 = ((icmp_ln155_1_fu_583_p2[0:0] == 1'b1) ? ClipMax_read : trunc_ln6_fu_587_p4);

assign sext_ln147_2_fu_379_p1 = mul_ln147_1_reg_781;

assign sext_ln147_3_fu_382_p1 = mul_ln147_2_reg_787;

assign sext_ln147_4_fu_388_p1 = grp_fu_633_p3;

assign sext_ln147_5_fu_405_p1 = $signed(add_ln147_1_fu_395_p2);

assign sext_ln149_2_fu_425_p1 = mul_ln149_1_reg_798;

assign sext_ln149_3_fu_428_p1 = mul_ln149_2_reg_804;

assign sext_ln149_4_fu_434_p1 = grp_fu_642_p3;

assign sext_ln149_5_fu_451_p1 = $signed(add_ln149_1_fu_441_p2);

assign sext_ln151_2_fu_471_p1 = mul_ln151_1_reg_815;

assign sext_ln151_3_fu_474_p1 = mul_ln151_2_reg_821;

assign sext_ln151_4_fu_480_p1 = grp_fu_651_p3;

assign sext_ln151_5_fu_497_p1 = $signed(add_ln151_1_fu_487_p2);

assign stream_csc_din = {{{select_ln155_1_reg_880}, {select_ln154_1_reg_885}}, {select_ln153_1_reg_875}};

assign trunc_ln147_1_fu_401_p1 = add_ln147_4_fu_391_p2[21:0];

assign trunc_ln147_fu_385_p1 = grp_fu_633_p3[21:0];

assign trunc_ln149_1_fu_447_p1 = add_ln149_4_fu_437_p2[21:0];

assign trunc_ln149_fu_431_p1 = grp_fu_642_p3[21:0];

assign trunc_ln151_1_fu_493_p1 = add_ln151_4_fu_483_p2[21:0];

assign trunc_ln151_fu_477_p1 = grp_fu_651_p3[21:0];

assign trunc_ln4_fu_537_p4 = {{add_ln147_3_fu_517_p2[21:12]}};

assign trunc_ln5_fu_569_p4 = {{add_ln149_3_fu_521_p2[21:12]}};

assign trunc_ln6_fu_587_p4 = {{add_ln151_3_fu_525_p2[21:12]}};

assign x_4_fu_277_p2 = (ap_sig_allocacmp_x_3 + 14'd1);

assign zext_ln61_1_fu_316_p1 = Gpix_reg_759_pp0_iter2_reg;

assign zext_ln61_2_fu_319_p1 = trunc_ln_reg_771_pp0_iter2_reg;

assign zext_ln61_fu_302_p1 = Rpix_fu_288_p1;

assign zext_ln89_1_cast_fu_223_p1 = zext_ln89_1;

assign zext_ln89_cast_fu_219_p1 = zext_ln89;

always @ (posedge ap_clk) begin
    zext_ln89_cast_reg_696[15:10] <= 6'b000000;
    zext_ln89_1_cast_reg_703[15:10] <= 6'b000000;
end

endmodule //bd_d92b_csc_0_v_csc_core_Pipeline_VITIS_LOOP_91_2
