// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_demosaic_0_0_AXIvideo2MultiBayer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        imgBayer_din,
        imgBayer_num_data_valid,
        imgBayer_fifo_cap,
        imgBayer_full_n,
        imgBayer_write,
        Height,
        WidthIn
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [0:0] s_axis_video_TKEEP;
input  [0:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [7:0] imgBayer_din;
input  [1:0] imgBayer_num_data_valid;
input  [1:0] imgBayer_fifo_cap;
input   imgBayer_full_n;
output   imgBayer_write;
input  [15:0] Height;
input  [15:0] WidthIn;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgBayer_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [12:0] trunc_ln101_fu_248_p1;
reg   [12:0] trunc_ln101_reg_365;
reg    ap_block_state1;
wire   [11:0] trunc_ln101_1_fu_262_p1;
reg   [11:0] trunc_ln101_1_reg_370;
wire    ap_CS_fsm_state2;
wire   [12:0] grp_reg_unsigned_short_s_fu_266_ap_return;
reg   [12:0] cols_reg_375;
wire    ap_CS_fsm_state4;
wire   [0:0] cmp10142_fu_274_p2;
reg   [0:0] cmp10142_reg_383;
wire   [0:0] icmp_ln118_fu_283_p2;
reg   [0:0] icmp_ln118_reg_387;
wire    ap_CS_fsm_state5;
wire   [11:0] i_4_fu_288_p2;
reg   [11:0] i_4_reg_391;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY;
wire   [7:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_last_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_last_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_ready;
wire   [7:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_din;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_write;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out_ap_vld;
wire   [7:0] grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_axi_data_3_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_axi_data_3_out_ap_vld;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_done;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_idle;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_ready;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_s_axis_video_TREADY;
wire   [7:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out;
wire    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out_ap_vld;
wire   [12:0] grp_reg_unsigned_short_s_fu_242_d;
wire   [12:0] grp_reg_unsigned_short_s_fu_242_ap_return;
reg    grp_reg_unsigned_short_s_fu_242_ap_ce;
reg    ap_block_state1_ignore_call15;
reg    grp_reg_unsigned_short_s_fu_266_ap_ce;
wire    ap_CS_fsm_state3;
reg   [0:0] axi_last_2_reg_122;
wire    ap_CS_fsm_state11;
reg   [7:0] axi_data_2_lcssa_reg_132;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state6;
reg   [0:0] axi_last_2_lcssa_reg_142;
reg   [0:0] eol_0_lcssa_reg_153;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg;
reg   [7:0] axi_data_2_fu_86;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg   [0:0] axi_last_4_loc_fu_94;
reg   [11:0] i_fu_82;
reg   [0:0] sof_fu_90;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [7:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [0:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [0:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 11'd1;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg = 1'b0;
end

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out),
    .axi_data_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out_ap_vld),
    .axi_last_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_last_out_ap_vld)
);

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_width grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .imgBayer_din(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_din),
    .imgBayer_num_data_valid(2'd0),
    .imgBayer_fifo_cap(2'd0),
    .imgBayer_full_n(imgBayer_full_n),
    .imgBayer_write(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_write),
    .sof_5(sof_fu_90),
    .axi_last_2(axi_last_2_reg_122),
    .axi_data_2(axi_data_2_fu_86),
    .cols(cols_reg_375),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .eol_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out_ap_vld),
    .axi_data_3_out(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_axi_data_3_out),
    .axi_data_3_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_axi_data_3_out_ap_vld)
);

design_1_v_demosaic_0_0_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start),
    .ap_done(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_done),
    .ap_idle(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_idle),
    .ap_ready(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .axi_data_2_lcssa(axi_data_2_lcssa_reg_132),
    .axi_last_2_lcssa(axi_last_2_lcssa_reg_142),
    .eol_0_lcssa(eol_0_lcssa_reg_153),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TREADY(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .axi_data_4_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out),
    .axi_data_4_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out_ap_vld),
    .axi_last_4_out(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out),
    .axi_last_4_out_ap_vld(grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out_ap_vld)
);

design_1_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_242(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(grp_reg_unsigned_short_s_fu_242_d),
    .ap_return(grp_reg_unsigned_short_s_fu_242_ap_return),
    .ap_ce(grp_reg_unsigned_short_s_fu_242_ap_ce)
);

design_1_v_demosaic_0_0_reg_unsigned_short_s grp_reg_unsigned_short_s_fu_266(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .d(trunc_ln101_reg_365),
    .ap_return(grp_reg_unsigned_short_s_fu_266_ap_return),
    .ap_ce(grp_reg_unsigned_short_s_fu_266_ap_ce)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 8 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

design_1_v_demosaic_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln118_reg_387 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln118_reg_387 == 1'd0) & (cmp10142_reg_383 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out_ap_vld == 1'b1))) begin
        axi_data_2_fu_86 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_data_4_out;
    end else if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        axi_data_2_fu_86 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_data_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_reg_387 == 1'd0) & (cmp10142_reg_383 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        axi_data_2_lcssa_reg_132 <= axi_data_2_fu_86;
    end else if (((cmp10142_reg_383 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_data_2_lcssa_reg_132 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_axi_data_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_reg_387 == 1'd0) & (cmp10142_reg_383 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        axi_last_2_lcssa_reg_142 <= axi_last_2_reg_122;
    end else if (((cmp10142_reg_383 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        axi_last_2_lcssa_reg_142 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        axi_last_2_reg_122 <= axi_last_4_loc_fu_94;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_2_reg_122 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln118_reg_387 == 1'd0) & (cmp10142_reg_383 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        eol_0_lcssa_reg_153 <= 1'd0;
    end else if (((cmp10142_reg_383 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        eol_0_lcssa_reg_153 <= grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_eol_out;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_82 <= 12'd0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        i_fu_82 <= i_4_reg_391;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        sof_fu_90 <= 1'd1;
    end else if (((cmp10142_reg_383 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        sof_fu_90 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out_ap_vld == 1'b1))) begin
        axi_last_4_loc_fu_94 <= grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_axi_last_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp10142_reg_383 <= cmp10142_fu_274_p2;
        cols_reg_375 <= grp_reg_unsigned_short_s_fu_266_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_4_reg_391 <= i_4_fu_288_p2;
        icmp_ln118_reg_387 <= icmp_ln118_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln101_1_reg_370 <= trunc_ln101_1_fu_262_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        trunc_ln101_reg_365 <= trunc_ln101_fu_248_p1;
    end
end

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln118_reg_387 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln118_reg_387 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_s_fu_242_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_242_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_reg_unsigned_short_s_fu_266_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_s_fu_266_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        imgBayer_write = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_write;
    end else begin
        imgBayer_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY_int_regslice = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln118_reg_387 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln118_reg_387 == 1'd0) & (cmp10142_reg_383 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call15 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp10142_fu_274_p2 = ((grp_reg_unsigned_short_s_fu_266_ap_return == 13'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_eol_fu_212_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_wait_for_start_fu_165_ap_start_reg;

assign grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_ap_start_reg;

assign grp_reg_unsigned_short_s_fu_242_d = Height[12:0];

assign i_4_fu_288_p2 = (i_fu_82 + 12'd1);

assign icmp_ln118_fu_283_p2 = ((i_fu_82 == trunc_ln101_1_reg_370) ? 1'b1 : 1'b0);

assign imgBayer_din = grp_AXIvideo2MultiBayer_Pipeline_loop_width_fu_185_imgBayer_din;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign trunc_ln101_1_fu_262_p1 = grp_reg_unsigned_short_s_fu_242_ap_return[11:0];

assign trunc_ln101_fu_248_p1 = WidthIn[12:0];

endmodule //design_1_v_demosaic_0_0_AXIvideo2MultiBayer
