// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        img_dout,
        img_num_data_valid,
        img_fifo_cap,
        img_empty_n,
        img_read,
        bytePlanes_din,
        bytePlanes_num_data_valid,
        bytePlanes_fifo_cap,
        bytePlanes_full_n,
        bytePlanes_write,
        Height_dout,
        Height_num_data_valid,
        Height_fifo_cap,
        Height_empty_n,
        Height_read,
        WidthInPix_dout,
        WidthInPix_num_data_valid,
        WidthInPix_fifo_cap,
        WidthInPix_empty_n,
        WidthInPix_read,
        WidthInBytes_dout,
        WidthInBytes_num_data_valid,
        WidthInBytes_fifo_cap,
        WidthInBytes_empty_n,
        WidthInBytes_read,
        VideoFormat_dout,
        VideoFormat_num_data_valid,
        VideoFormat_fifo_cap,
        VideoFormat_empty_n,
        VideoFormat_read,
        WidthInBytes_c_din,
        WidthInBytes_c_num_data_valid,
        WidthInBytes_c_fifo_cap,
        WidthInBytes_c_full_n,
        WidthInBytes_c_write,
        height_c_din,
        height_c_num_data_valid,
        height_c_fifo_cap,
        height_c_full_n,
        height_c_write
);

parameter    ap_ST_fsm_state1 = 21'd1;
parameter    ap_ST_fsm_state2 = 21'd2;
parameter    ap_ST_fsm_state3 = 21'd4;
parameter    ap_ST_fsm_state4 = 21'd8;
parameter    ap_ST_fsm_state5 = 21'd16;
parameter    ap_ST_fsm_state6 = 21'd32;
parameter    ap_ST_fsm_state7 = 21'd64;
parameter    ap_ST_fsm_state8 = 21'd128;
parameter    ap_ST_fsm_state9 = 21'd256;
parameter    ap_ST_fsm_state10 = 21'd512;
parameter    ap_ST_fsm_state11 = 21'd1024;
parameter    ap_ST_fsm_state12 = 21'd2048;
parameter    ap_ST_fsm_state13 = 21'd4096;
parameter    ap_ST_fsm_state14 = 21'd8192;
parameter    ap_ST_fsm_state15 = 21'd16384;
parameter    ap_ST_fsm_state16 = 21'd32768;
parameter    ap_ST_fsm_state17 = 21'd65536;
parameter    ap_ST_fsm_state18 = 21'd131072;
parameter    ap_ST_fsm_state19 = 21'd262144;
parameter    ap_ST_fsm_state20 = 21'd524288;
parameter    ap_ST_fsm_state21 = 21'd1048576;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [29:0] img_dout;
input  [1:0] img_num_data_valid;
input  [1:0] img_fifo_cap;
input   img_empty_n;
output   img_read;
output  [63:0] bytePlanes_din;
input  [10:0] bytePlanes_num_data_valid;
input  [10:0] bytePlanes_fifo_cap;
input   bytePlanes_full_n;
output   bytePlanes_write;
input  [11:0] Height_dout;
input  [1:0] Height_num_data_valid;
input  [1:0] Height_fifo_cap;
input   Height_empty_n;
output   Height_read;
input  [2:0] WidthInPix_dout;
input  [1:0] WidthInPix_num_data_valid;
input  [1:0] WidthInPix_fifo_cap;
input   WidthInPix_empty_n;
output   WidthInPix_read;
input  [14:0] WidthInBytes_dout;
input  [2:0] WidthInBytes_num_data_valid;
input  [2:0] WidthInBytes_fifo_cap;
input   WidthInBytes_empty_n;
output   WidthInBytes_read;
input  [5:0] VideoFormat_dout;
input  [2:0] VideoFormat_num_data_valid;
input  [2:0] VideoFormat_fifo_cap;
input   VideoFormat_empty_n;
output   VideoFormat_read;
output  [14:0] WidthInBytes_c_din;
input  [1:0] WidthInBytes_c_num_data_valid;
input  [1:0] WidthInBytes_c_fifo_cap;
input   WidthInBytes_c_full_n;
output   WidthInBytes_c_write;
output  [11:0] height_c_din;
input  [1:0] height_c_num_data_valid;
input  [1:0] height_c_fifo_cap;
input   height_c_full_n;
output   height_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg img_read;
reg[63:0] bytePlanes_din;
reg bytePlanes_write;
reg Height_read;
reg WidthInPix_read;
reg WidthInBytes_read;
reg VideoFormat_read;
reg WidthInBytes_c_write;
reg height_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [20:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    Height_blk_n;
reg    WidthInPix_blk_n;
reg    WidthInBytes_blk_n;
reg    VideoFormat_blk_n;
reg    WidthInBytes_c_blk_n;
reg    height_c_blk_n;
wire   [5:0] VideoFormat_read_read_fu_246_p2;
reg   [5:0] VideoFormat_read_reg_1170;
reg    ap_block_state1;
reg   [11:0] Height_read_reg_1174;
reg   [2:0] widthInPix_1_reg_1184;
reg   [14:0] widthInPix_reg_1195;
wire   [12:0] trunc_ln915_1_fu_402_p4;
reg   [12:0] trunc_ln915_1_reg_1215;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln920_fu_416_p2;
reg   [0:0] icmp_ln920_reg_1220;
wire   [12:0] sub585_fu_430_p2;
reg   [12:0] sub585_reg_1225;
wire   [0:0] icmp46_fu_446_p2;
reg   [0:0] icmp46_reg_1230;
wire   [0:0] cmp588_2_fu_452_p2;
reg   [0:0] cmp588_2_reg_1235;
wire   [0:0] icmp49_fu_468_p2;
reg   [0:0] icmp49_reg_1240;
wire   [0:0] cmp588_4_fu_474_p2;
reg   [0:0] cmp588_4_reg_1245;
wire   [0:0] cmp588_5_fu_480_p2;
reg   [0:0] cmp588_5_reg_1250;
wire   [0:0] cmp588_6_fu_486_p2;
reg   [0:0] cmp588_6_reg_1255;
wire   [12:0] add_ln868_fu_535_p2;
reg   [12:0] add_ln868_reg_1270;
wire    ap_CS_fsm_state5;
reg   [10:0] trunc_ln6_reg_1275;
wire    ap_CS_fsm_state6;
wire   [0:0] grp_fu_378_p2;
reg   [0:0] icmp_ln872_reg_1281;
wire    ap_CS_fsm_state7;
wire   [11:0] sub473_fu_631_p2;
reg   [11:0] sub473_reg_1286;
wire   [0:0] icmp37_fu_647_p2;
reg   [0:0] icmp37_reg_1291;
wire   [0:0] cmp476_2_fu_653_p2;
reg   [0:0] cmp476_2_reg_1296;
wire   [0:0] icmp40_fu_669_p2;
reg   [0:0] icmp40_reg_1301;
wire   [0:0] cmp476_4_fu_675_p2;
reg   [0:0] cmp476_4_reg_1306;
wire   [0:0] cmp476_5_fu_681_p2;
reg   [0:0] cmp476_5_reg_1311;
wire   [0:0] cmp476_6_fu_687_p2;
reg   [0:0] cmp476_6_reg_1316;
wire   [0:0] icmp43_fu_703_p2;
reg   [0:0] icmp43_reg_1321;
wire   [0:0] cmp529_2_fu_709_p2;
reg   [0:0] cmp529_2_reg_1326;
wire   [12:0] add_ln745_fu_772_p2;
reg   [12:0] add_ln745_reg_1344;
wire    ap_CS_fsm_state10;
reg   [10:0] trunc_ln3_reg_1349;
wire    ap_CS_fsm_state11;
reg   [0:0] icmp_ln749_reg_1355;
wire    ap_CS_fsm_state12;
wire   [11:0] sub336_fu_868_p2;
reg   [11:0] sub336_reg_1360;
wire   [0:0] icmp28_fu_884_p2;
reg   [0:0] icmp28_reg_1365;
wire   [0:0] cmp339_2_fu_890_p2;
reg   [0:0] cmp339_2_reg_1370;
wire   [0:0] icmp31_fu_906_p2;
reg   [0:0] icmp31_reg_1375;
wire   [0:0] cmp339_4_fu_912_p2;
reg   [0:0] cmp339_4_reg_1380;
wire   [0:0] cmp339_5_fu_918_p2;
reg   [0:0] cmp339_5_reg_1385;
wire   [0:0] cmp339_6_fu_924_p2;
reg   [0:0] cmp339_6_reg_1390;
wire   [0:0] icmp34_fu_940_p2;
reg   [0:0] icmp34_reg_1395;
wire   [0:0] cmp390_2_fu_946_p2;
reg   [0:0] cmp390_2_reg_1400;
wire   [12:0] trunc_ln496_1_fu_961_p4;
reg   [12:0] trunc_ln496_1_reg_1412;
wire    ap_CS_fsm_state14;
wire   [0:0] icmp_ln501_fu_984_p2;
reg   [0:0] icmp_ln501_reg_1417;
wire   [12:0] sub200_fu_998_p2;
reg   [12:0] sub200_reg_1422;
wire   [0:0] icmp_fu_1014_p2;
reg   [0:0] icmp_reg_1427;
wire   [0:0] cmp203_2_fu_1020_p2;
reg   [0:0] cmp203_2_reg_1432;
wire   [12:0] trunc_ln457_1_fu_1040_p4;
reg   [12:0] trunc_ln457_1_reg_1450;
wire   [0:0] xor_ln462_fu_1050_p2;
reg   [0:0] xor_ln462_reg_1455;
wire   [12:0] sub109_fu_1056_p2;
reg   [12:0] sub109_reg_1460;
wire   [12:0] trunc_ln378_1_fu_1119_p4;
reg   [12:0] trunc_ln378_1_reg_1484;
wire    ap_CS_fsm_state19;
wire   [0:0] xor_ln383_fu_1129_p2;
reg   [0:0] xor_ln383_reg_1489;
wire   [12:0] sub25_fu_1135_p2;
reg   [12:0] sub25_reg_1494;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_ready;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_ready;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o_ap_vld;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_done;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_idle;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_ready;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_din;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_write;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_img_read;
wire   [63:0] grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o;
wire    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o_ap_vld;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln927_fu_500_p2;
wire    ap_CS_fsm_state4;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln884_fu_718_p2;
wire    ap_CS_fsm_state9;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg;
wire   [0:0] icmp_ln760_fu_737_p2;
wire    ap_CS_fsm_state13;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg;
wire    ap_CS_fsm_state15;
wire   [0:0] icmp_ln508_fu_1075_p2;
wire    ap_CS_fsm_state16;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg;
wire    ap_CS_fsm_state17;
wire   [0:0] icmp_ln469_fu_1094_p2;
wire    ap_CS_fsm_state18;
reg   [63:0] out_pix_1_fu_230;
reg    grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg;
wire    ap_CS_fsm_state20;
wire   [0:0] icmp_ln390_fu_1154_p2;
wire    ap_CS_fsm_state21;
reg   [63:0] out_pix_fu_238;
reg   [11:0] y_3_fu_214;
wire   [11:0] y_17_fu_505_p2;
reg   [11:0] y_5_fu_218;
wire   [11:0] y_15_fu_723_p2;
reg   [11:0] y_4_fu_222;
wire   [11:0] y_13_fu_742_p2;
reg   [11:0] y_2_fu_226;
wire   [11:0] y_11_fu_1080_p2;
reg   [11:0] y_1_fu_234;
wire   [11:0] y_9_fu_1099_p2;
reg   [11:0] y_fu_242;
wire   [11:0] y_7_fu_1159_p2;
wire   [15:0] zext_ln915_fu_393_p1;
wire   [15:0] add_ln915_fu_396_p2;
wire   [2:0] remainPix_4_fu_390_p1;
wire   [3:0] zext_ln918_fu_412_p1;
wire   [3:0] remainPix_5_fu_422_p3;
wire   [2:0] tmp_9_fu_436_p4;
wire   [1:0] tmp_10_fu_458_p4;
wire   [15:0] zext_ln866_fu_516_p1;
wire   [15:0] add_ln866_fu_519_p2;
wire   [12:0] trunc_ln5_fu_525_p4;
wire   [12:0] mul_ln868_fu_549_p0;
wire   [14:0] mul_ln868_fu_549_p1;
wire   [26:0] mul_ln868_fu_549_p2;
wire   [3:0] zext_ln870_fu_568_p1;
wire   [7:0] shl_ln1_fu_579_p3;
wire   [5:0] shl_ln878_1_fu_590_p3;
wire   [8:0] zext_ln878_fu_586_p1;
wire   [8:0] zext_ln878_1_fu_597_p1;
wire   [8:0] sub_ln878_fu_601_p2;
wire   [8:0] add_ln878_fu_607_p2;
wire   [2:0] trunc_ln7_fu_613_p4;
wire   [11:0] zext_ln868_fu_565_p1;
wire   [3:0] remainPix_3_fu_571_p3;
wire   [2:0] tmp_6_fu_637_p4;
wire   [1:0] tmp_7_fu_659_p4;
wire   [2:0] remainTrx_1_fu_623_p3;
wire   [1:0] tmp_8_fu_693_p4;
wire   [15:0] zext_ln743_fu_753_p1;
wire   [15:0] add_ln743_fu_756_p2;
wire   [12:0] trunc_ln2_fu_762_p4;
wire   [12:0] mul_ln745_fu_786_p0;
wire   [14:0] mul_ln745_fu_786_p1;
wire   [26:0] mul_ln745_fu_786_p2;
wire   [3:0] zext_ln747_fu_805_p1;
wire   [7:0] shl_ln_fu_816_p3;
wire   [5:0] shl_ln755_1_fu_827_p3;
wire   [8:0] zext_ln755_fu_823_p1;
wire   [8:0] zext_ln755_1_fu_834_p1;
wire   [8:0] sub_ln755_fu_838_p2;
wire   [8:0] add_ln755_fu_844_p2;
wire   [2:0] trunc_ln4_fu_850_p4;
wire   [11:0] zext_ln745_fu_802_p1;
wire   [3:0] remainPix_2_fu_808_p3;
wire   [2:0] tmp_3_fu_874_p4;
wire   [1:0] tmp_4_fu_896_p4;
wire   [2:0] remainTrx_fu_860_p3;
wire   [1:0] tmp_5_fu_930_p4;
wire   [15:0] zext_ln496_fu_952_p1;
wire   [15:0] add_ln496_fu_955_p2;
wire   [1:0] remainPix_fu_971_p4;
wire   [2:0] zext_ln499_fu_980_p1;
wire   [2:0] remainPix_1_fu_990_p3;
wire   [1:0] tmp_2_fu_1004_p4;
wire   [15:0] zext_ln457_fu_1031_p1;
wire   [15:0] add_ln457_fu_1034_p2;
wire   [0:0] grp_fu_383_p3;
wire   [15:0] zext_ln378_fu_1110_p1;
wire   [15:0] add_ln378_fu_1113_p2;
reg   [20:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire   [26:0] mul_ln745_fu_786_p00;
wire   [26:0] mul_ln868_fu_549_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 21'd1;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg = 1'b0;
#0 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg = 1'b0;
end

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_img_read),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_write),
    .trunc_ln915_1(trunc_ln915_1_reg_1215),
    .icmp_ln920(icmp_ln920_reg_1220),
    .cmp588_6(cmp588_6_reg_1255),
    .cmp588_5(cmp588_5_reg_1250),
    .cmp588_4(cmp588_4_reg_1245),
    .cmp588_3(icmp49_reg_1240),
    .cmp588_2(cmp588_2_reg_1235),
    .sub585_cast16(sub585_reg_1225),
    .cmp588_1(icmp46_reg_1230)
);

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_img_read),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_write),
    .trunc_ln6(trunc_ln6_reg_1275),
    .cmp529_2(cmp529_2_reg_1326),
    .cmp529_1(icmp43_reg_1321),
    .icmp_ln872(icmp_ln872_reg_1281),
    .cmp476_6(cmp476_6_reg_1316),
    .cmp476_5(cmp476_5_reg_1311),
    .cmp476_4(cmp476_4_reg_1306),
    .cmp476_3(icmp40_reg_1301),
    .cmp476_2(cmp476_2_reg_1296),
    .sub473(sub473_reg_1286),
    .cmp476_1(icmp37_reg_1291)
);

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_img_read),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_write),
    .trunc_ln3(trunc_ln3_reg_1349),
    .cmp390_2(cmp390_2_reg_1400),
    .cmp390_1(icmp34_reg_1395),
    .icmp_ln749(icmp_ln749_reg_1355),
    .cmp339_6(cmp339_6_reg_1390),
    .cmp339_5(cmp339_5_reg_1385),
    .cmp339_4(cmp339_4_reg_1380),
    .cmp339_3(icmp31_reg_1375),
    .cmp339_2(cmp339_2_reg_1370),
    .sub336(sub336_reg_1360),
    .cmp339_1(icmp28_reg_1365)
);

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_ready),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_img_read),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_write),
    .trunc_ln496_1(trunc_ln496_1_reg_1412),
    .icmp_ln501(icmp_ln501_reg_1417),
    .cmp203_2(cmp203_2_reg_1432),
    .sub200_cast15(sub200_reg_1422),
    .cmp203_1(icmp_reg_1427)
);

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_ready),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_write),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_img_read),
    .trunc_ln457_1(trunc_ln457_1_reg_1450),
    .sext_ln469(sub109_reg_1460),
    .icmp_ln462(xor_ln462_reg_1455),
    .out_pix_4_out_i(out_pix_1_fu_230),
    .out_pix_4_out_o(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o),
    .out_pix_4_out_o_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o_ap_vld)
);

design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1 grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start),
    .ap_done(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_done),
    .ap_idle(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_idle),
    .ap_ready(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_ready),
    .bytePlanes_din(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_din),
    .bytePlanes_num_data_valid(11'd0),
    .bytePlanes_fifo_cap(11'd0),
    .bytePlanes_full_n(bytePlanes_full_n),
    .bytePlanes_write(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_write),
    .img_dout(img_dout),
    .img_num_data_valid(2'd0),
    .img_fifo_cap(2'd0),
    .img_empty_n(img_empty_n),
    .img_read(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_img_read),
    .trunc_ln378_1(trunc_ln378_1_reg_1484),
    .sext_ln390(sub25_reg_1494),
    .icmp_ln383(xor_ln383_reg_1489),
    .out_pix_2_out_i(out_pix_fu_238),
    .out_pix_2_out_o(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o),
    .out_pix_2_out_o_ap_vld(grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o_ap_vld)
);

design_1_v_frmbuf_wr_0_0_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U115(
    .din0(mul_ln868_fu_549_p0),
    .din1(mul_ln868_fu_549_p1),
    .dout(mul_ln868_fu_549_p2)
);

design_1_v_frmbuf_wr_0_0_mul_13ns_15ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 15 ),
    .dout_WIDTH( 27 ))
mul_13ns_15ns_27_1_1_U116(
    .din0(mul_ln745_fu_786_p0),
    .din1(mul_ln745_fu_786_p1),
    .dout(mul_ln745_fu_786_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln884_fu_718_p2 == 1'd1) & (6'd29 == VideoFormat_read_reg_1170)) | (~(6'd29 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd1))) | (~(6'd21 == VideoFormat_read_reg_1170) & ~(6'd20 == VideoFormat_read_reg_1170) & ~(6'd29 == VideoFormat_read_reg_1170))))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln390_fu_1154_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln469_fu_1094_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln508_fu_1075_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) & (((6'd21 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd0)) | ((icmp_ln760_fu_737_p2 == 1'd0) & (6'd20 == VideoFormat_read_reg_1170))))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln884_fu_718_p2 == 1'd0) & (6'd29 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln927_fu_500_p2 == 1'd0) & (6'd24 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg <= 1'b1;
        end else if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_ready == 1'b1)) begin
            grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ((6'd16 == VideoFormat_read_reg_1170) | (6'd15 == VideoFormat_read_reg_1170)))) begin
        out_pix_1_fu_230 <= 64'd0;
    end else if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        out_pix_1_fu_230 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_out_pix_4_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        out_pix_fu_238 <= 64'd0;
    end else if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
        out_pix_fu_238 <= grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_out_pix_2_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ((6'd16 == VideoFormat_read_reg_1170) | (6'd15 == VideoFormat_read_reg_1170)))) begin
        y_1_fu_234 <= 12'd0;
    end else if (((icmp_ln469_fu_1094_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state17))) begin
        y_1_fu_234 <= y_9_fu_1099_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((6'd12 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state14))) begin
        y_2_fu_226 <= 12'd0;
    end else if (((icmp_ln508_fu_1075_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state15))) begin
        y_2_fu_226 <= y_11_fu_1080_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        y_3_fu_214 <= 12'd0;
    end else if (((icmp_ln927_fu_500_p2 == 1'd0) & (6'd24 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state3))) begin
        y_3_fu_214 <= y_17_fu_505_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (((6'd21 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd0)) | ((icmp_ln760_fu_737_p2 == 1'd0) & (6'd20 == VideoFormat_read_reg_1170))))) begin
        y_4_fu_222 <= y_13_fu_742_p2;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        y_4_fu_222 <= 12'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        y_5_fu_218 <= 12'd0;
    end else if (((icmp_ln884_fu_718_p2 == 1'd0) & (6'd29 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state8))) begin
        y_5_fu_218 <= y_15_fu_723_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        y_fu_242 <= 12'd0;
    end else if (((icmp_ln390_fu_1154_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state20))) begin
        y_fu_242 <= y_7_fu_1159_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read_reg_1174 <= Height_dout;
        VideoFormat_read_reg_1170 <= VideoFormat_dout;
        widthInPix_1_reg_1184 <= WidthInPix_dout;
        widthInPix_reg_1195 <= WidthInBytes_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln745_reg_1344 <= add_ln745_fu_772_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln868_reg_1270 <= add_ln868_fu_535_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((6'd12 == VideoFormat_read_reg_1170) & (1'b1 == ap_CS_fsm_state14))) begin
        cmp203_2_reg_1432 <= cmp203_2_fu_1020_p2;
        icmp_ln501_reg_1417 <= icmp_ln501_fu_984_p2;
        icmp_reg_1427 <= icmp_fu_1014_p2;
        sub200_reg_1422 <= sub200_fu_998_p2;
        trunc_ln496_1_reg_1412 <= {{add_ln496_fu_955_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        cmp339_2_reg_1370 <= cmp339_2_fu_890_p2;
        cmp339_4_reg_1380 <= cmp339_4_fu_912_p2;
        cmp339_5_reg_1385 <= cmp339_5_fu_918_p2;
        cmp339_6_reg_1390 <= cmp339_6_fu_924_p2;
        cmp390_2_reg_1400 <= cmp390_2_fu_946_p2;
        icmp28_reg_1365 <= icmp28_fu_884_p2;
        icmp31_reg_1375 <= icmp31_fu_906_p2;
        icmp34_reg_1395 <= icmp34_fu_940_p2;
        icmp_ln749_reg_1355 <= grp_fu_378_p2;
        sub336_reg_1360 <= sub336_fu_868_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        cmp476_2_reg_1296 <= cmp476_2_fu_653_p2;
        cmp476_4_reg_1306 <= cmp476_4_fu_675_p2;
        cmp476_5_reg_1311 <= cmp476_5_fu_681_p2;
        cmp476_6_reg_1316 <= cmp476_6_fu_687_p2;
        cmp529_2_reg_1326 <= cmp529_2_fu_709_p2;
        icmp37_reg_1291 <= icmp37_fu_647_p2;
        icmp40_reg_1301 <= icmp40_fu_669_p2;
        icmp43_reg_1321 <= icmp43_fu_703_p2;
        icmp_ln872_reg_1281 <= grp_fu_378_p2;
        sub473_reg_1286 <= sub473_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp588_2_reg_1235 <= cmp588_2_fu_452_p2;
        cmp588_4_reg_1245 <= cmp588_4_fu_474_p2;
        cmp588_5_reg_1250 <= cmp588_5_fu_480_p2;
        cmp588_6_reg_1255 <= cmp588_6_fu_486_p2;
        icmp46_reg_1230 <= icmp46_fu_446_p2;
        icmp49_reg_1240 <= icmp49_fu_468_p2;
        icmp_ln920_reg_1220 <= icmp_ln920_fu_416_p2;
        sub585_reg_1225 <= sub585_fu_430_p2;
        trunc_ln915_1_reg_1215 <= {{add_ln915_fu_396_p2[15:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state14) & ((6'd16 == VideoFormat_read_reg_1170) | (6'd15 == VideoFormat_read_reg_1170)))) begin
        sub109_reg_1460 <= sub109_fu_1056_p2;
        trunc_ln457_1_reg_1450 <= {{add_ln457_fu_1034_p2[15:3]}};
        xor_ln462_reg_1455 <= xor_ln462_fu_1050_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        sub25_reg_1494 <= sub25_fu_1135_p2;
        trunc_ln378_1_reg_1484 <= {{add_ln378_fu_1113_p2[15:3]}};
        xor_ln383_reg_1489 <= xor_ln383_fu_1129_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        trunc_ln3_reg_1349 <= {{mul_ln745_fu_786_p2[25:15]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        trunc_ln6_reg_1275 <= {{mul_ln868_fu_549_p2[25:15]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_blk_n = Height_empty_n;
    end else begin
        Height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        Height_read = 1'b1;
    end else begin
        Height_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_blk_n = VideoFormat_empty_n;
    end else begin
        VideoFormat_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        VideoFormat_read = 1'b1;
    end else begin
        VideoFormat_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_blk_n = WidthInBytes_empty_n;
    end else begin
        WidthInBytes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_blk_n = WidthInBytes_c_full_n;
    end else begin
        WidthInBytes_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_c_write = 1'b1;
    end else begin
        WidthInBytes_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInBytes_read = 1'b1;
    end else begin
        WidthInBytes_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInPix_blk_n = WidthInPix_empty_n;
    end else begin
        WidthInPix_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        WidthInPix_read = 1'b1;
    end else begin
        WidthInPix_read = 1'b0;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_done == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln884_fu_718_p2 == 1'd1) & (6'd29 == VideoFormat_read_reg_1170)) | (~(6'd29 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd1))) | (~(6'd21 == VideoFormat_read_reg_1170) & ~(6'd20 == VideoFormat_read_reg_1170) & ~(6'd29 == VideoFormat_read_reg_1170))))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln884_fu_718_p2 == 1'd1) & (6'd29 == VideoFormat_read_reg_1170)) | (~(6'd29 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd1))) | (~(6'd21 == VideoFormat_read_reg_1170) & ~(6'd20 == VideoFormat_read_reg_1170) & ~(6'd29 == VideoFormat_read_reg_1170))))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_din;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_din;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_din;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_din;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_din;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_din;
    end else begin
        bytePlanes_din = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_bytePlanes_write;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_bytePlanes_write;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_bytePlanes_write;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_bytePlanes_write;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_bytePlanes_write;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        bytePlanes_write = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_bytePlanes_write;
    end else begin
        bytePlanes_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_blk_n = height_c_full_n;
    end else begin
        height_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_c_write = 1'b1;
    end else begin
        height_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_img_read;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_img_read;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_img_read;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_img_read;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_img_read;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        img_read = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_img_read;
    end else begin
        img_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd11 == VideoFormat_read_read_fu_246_p2) | (6'd10 == VideoFormat_read_read_fu_246_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd16 == VideoFormat_read_read_fu_246_p2) | ((6'd15 == VideoFormat_read_read_fu_246_p2) | (6'd12 == VideoFormat_read_read_fu_246_p2))))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd21 == VideoFormat_read_read_fu_246_p2) | (6'd20 == VideoFormat_read_read_fu_246_p2)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1) & ((6'd43 == VideoFormat_read_read_fu_246_p2) | ((6'd42 == VideoFormat_read_read_fu_246_p2) | ((6'd27 == VideoFormat_read_read_fu_246_p2) | ((6'd28 == VideoFormat_read_read_fu_246_p2) | ((6'd19 == VideoFormat_read_read_fu_246_p2) | ((6'd18 == VideoFormat_read_read_fu_246_p2) | ((6'd23 == VideoFormat_read_read_fu_246_p2) | ((6'd22 == VideoFormat_read_read_fu_246_p2) | ((6'd33 == VideoFormat_read_read_fu_246_p2) | ((6'd32 == VideoFormat_read_read_fu_246_p2) | ((6'd38 == VideoFormat_read_read_fu_246_p2) | ((6'd37 == VideoFormat_read_read_fu_246_p2) | ((6'd31 == VideoFormat_read_read_fu_246_p2) | ((6'd30 == VideoFormat_read_read_fu_246_p2) | ((6'd35 == VideoFormat_read_read_fu_246_p2) | (6'd36 == VideoFormat_read_read_fu_246_p2)))))))))))))))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (6'd29 == VideoFormat_read_read_fu_246_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~(6'd11 == VideoFormat_read_read_fu_246_p2) & ~(6'd42 == VideoFormat_read_read_fu_246_p2) & ~(6'd43 == VideoFormat_read_read_fu_246_p2) & ~(6'd24 == VideoFormat_read_read_fu_246_p2) & ~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & ~(6'd29 == VideoFormat_read_read_fu_246_p2) & ~(6'd35 == VideoFormat_read_read_fu_246_p2) & ~(6'd36 == VideoFormat_read_read_fu_246_p2) & ~(6'd30 == VideoFormat_read_read_fu_246_p2) & ~(6'd31 == VideoFormat_read_read_fu_246_p2) & ~(6'd20 == VideoFormat_read_read_fu_246_p2) & ~(6'd21 == VideoFormat_read_read_fu_246_p2) & ~(6'd37 == VideoFormat_read_read_fu_246_p2) & ~(6'd38 == VideoFormat_read_read_fu_246_p2) & ~(6'd32 == VideoFormat_read_read_fu_246_p2) & ~(6'd33 == VideoFormat_read_read_fu_246_p2) & ~(6'd22 == VideoFormat_read_read_fu_246_p2) & ~(6'd23 == VideoFormat_read_read_fu_246_p2) & ~(6'd18 == 
    VideoFormat_read_read_fu_246_p2) & ~(6'd19 == VideoFormat_read_read_fu_246_p2) & ~(6'd28 == VideoFormat_read_read_fu_246_p2) & ~(6'd12 == VideoFormat_read_read_fu_246_p2) & ~(6'd15 == VideoFormat_read_read_fu_246_p2) & ~(6'd16 == VideoFormat_read_read_fu_246_p2) & ~(6'd27 == VideoFormat_read_read_fu_246_p2) & ~(6'd10 == VideoFormat_read_read_fu_246_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0)) & (6'd24 == VideoFormat_read_read_fu_246_p2) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (((6'd0 == VideoFormat_read_reg_1170) | ((6'd1 == VideoFormat_read_reg_1170) | ((6'd2 == VideoFormat_read_reg_1170) | ((6'd3 == VideoFormat_read_reg_1170) | ((6'd4 == VideoFormat_read_reg_1170) | ((6'd5 == VideoFormat_read_reg_1170) | ((6'd6 == VideoFormat_read_reg_1170) | ((6'd7 == VideoFormat_read_reg_1170) | ((6'd8 == VideoFormat_read_reg_1170) | ((6'd9 == VideoFormat_read_reg_1170) | ((6'd13 == VideoFormat_read_reg_1170) | ((6'd14 == VideoFormat_read_reg_1170) | ((6'd17 == VideoFormat_read_reg_1170) | ((6'd25 == VideoFormat_read_reg_1170) | ((6'd26 == VideoFormat_read_reg_1170) | ((6'd34 == VideoFormat_read_reg_1170) | ((6'd39 == VideoFormat_read_reg_1170) | ((6'd40 == VideoFormat_read_reg_1170) | ((6'd41 == VideoFormat_read_reg_1170) | ((6'd44 == VideoFormat_read_reg_1170) | ((6'd45 == VideoFormat_read_reg_1170) | ((6'd46 == VideoFormat_read_reg_1170) | ((6'd47 == VideoFormat_read_reg_1170) | ((6'd48 == VideoFormat_read_reg_1170) | ((6'd49 == VideoFormat_read_reg_1170) | ((6'd50 
    == VideoFormat_read_reg_1170) | ((6'd51 == VideoFormat_read_reg_1170) | ((6'd52 == VideoFormat_read_reg_1170) | ((6'd53 == VideoFormat_read_reg_1170) | ((6'd54 == VideoFormat_read_reg_1170) | ((6'd55 == VideoFormat_read_reg_1170) | ((6'd56 == VideoFormat_read_reg_1170) | ((6'd57 == VideoFormat_read_reg_1170) | ((6'd58 == VideoFormat_read_reg_1170) | ((6'd59 == VideoFormat_read_reg_1170) | ((6'd60 == VideoFormat_read_reg_1170) | ((6'd61 == VideoFormat_read_reg_1170) | ((6'd62 == VideoFormat_read_reg_1170) | (6'd63 == VideoFormat_read_reg_1170))))))))))))))))))))))))))))))))))))))) | ((icmp_ln927_fu_500_p2 == 1'd1) & (6'd24 == VideoFormat_read_reg_1170))))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & ((((icmp_ln884_fu_718_p2 == 1'd1) & (6'd29 == VideoFormat_read_reg_1170)) | (~(6'd29 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd1))) | (~(6'd21 == VideoFormat_read_reg_1170) & ~(6'd20 == VideoFormat_read_reg_1170) & ~(6'd29 == VideoFormat_read_reg_1170))))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b1 == ap_CS_fsm_state8) & (((6'd21 == VideoFormat_read_reg_1170) & (icmp_ln760_fu_737_p2 == 1'd0)) | ((icmp_ln760_fu_737_p2 == 1'd0) & (6'd20 == VideoFormat_read_reg_1170))))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state13 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & ((6'd16 == VideoFormat_read_reg_1170) | (6'd15 == VideoFormat_read_reg_1170)))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((icmp_ln508_fu_1075_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((icmp_ln469_fu_1094_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((icmp_ln390_fu_1154_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state21 : begin
            if (((grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign VideoFormat_read_read_fu_246_p2 = VideoFormat_dout;

assign WidthInBytes_c_din = WidthInBytes_dout;

assign add_ln378_fu_1113_p2 = (zext_ln378_fu_1110_p1 + 16'd7);

assign add_ln457_fu_1034_p2 = (zext_ln457_fu_1031_p1 + 16'd7);

assign add_ln496_fu_955_p2 = (zext_ln496_fu_952_p1 + 16'd7);

assign add_ln743_fu_756_p2 = (zext_ln743_fu_753_p1 + 16'd7);

assign add_ln745_fu_772_p2 = (trunc_ln2_fu_762_p4 + 13'd2);

assign add_ln755_fu_844_p2 = (sub_ln755_fu_838_p2 + 9'd63);

assign add_ln866_fu_519_p2 = (zext_ln866_fu_516_p1 + 16'd7);

assign add_ln868_fu_535_p2 = (trunc_ln5_fu_525_p4 + 13'd2);

assign add_ln878_fu_607_p2 = (sub_ln878_fu_601_p2 + 9'd63);

assign add_ln915_fu_396_p2 = (zext_ln915_fu_393_p1 + 16'd7);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((height_c_full_n == 1'b0) | (ap_done_reg == 1'b1) | (1'b0 == WidthInBytes_c_full_n) | (1'b0 == VideoFormat_empty_n) | (1'b0 == WidthInBytes_empty_n) | (1'b0 == WidthInPix_empty_n) | (1'b0 == Height_empty_n) | (ap_start == 1'b0));
end

assign cmp203_2_fu_1020_p2 = ((remainPix_1_fu_990_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp339_2_fu_890_p2 = ((remainPix_2_fu_808_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp339_4_fu_912_p2 = ((remainPix_2_fu_808_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp339_5_fu_918_p2 = ((remainPix_2_fu_808_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp339_6_fu_924_p2 = ((remainPix_2_fu_808_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp390_2_fu_946_p2 = ((remainTrx_fu_860_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp476_2_fu_653_p2 = ((remainPix_3_fu_571_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp476_4_fu_675_p2 = ((remainPix_3_fu_571_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp476_5_fu_681_p2 = ((remainPix_3_fu_571_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp476_6_fu_687_p2 = ((remainPix_3_fu_571_p3 > 4'd6) ? 1'b1 : 1'b0);

assign cmp529_2_fu_709_p2 = ((remainTrx_1_fu_623_p3 > 3'd2) ? 1'b1 : 1'b0);

assign cmp588_2_fu_452_p2 = ((remainPix_5_fu_422_p3 > 4'd2) ? 1'b1 : 1'b0);

assign cmp588_4_fu_474_p2 = ((remainPix_5_fu_422_p3 > 4'd4) ? 1'b1 : 1'b0);

assign cmp588_5_fu_480_p2 = ((remainPix_5_fu_422_p3 > 4'd5) ? 1'b1 : 1'b0);

assign cmp588_6_fu_486_p2 = ((remainPix_5_fu_422_p3 > 4'd6) ? 1'b1 : 1'b0);

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_393_1_fu_366_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_472_5_fu_354_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_511_9_fu_341_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_763_13_fu_322_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_887_18_fu_303_ap_start_reg;

assign grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start = grp_MultiPixStream2Bytes_Pipeline_VITIS_LOOP_930_23_fu_286_ap_start_reg;

assign grp_fu_378_p2 = ((widthInPix_1_reg_1184 == 3'd0) ? 1'b1 : 1'b0);

assign grp_fu_383_p3 = widthInPix_reg_1195[32'd2];

assign height_c_din = Height_dout;

assign icmp28_fu_884_p2 = ((tmp_3_fu_874_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp31_fu_906_p2 = ((tmp_4_fu_896_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp34_fu_940_p2 = ((tmp_5_fu_930_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp37_fu_647_p2 = ((tmp_6_fu_637_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp40_fu_669_p2 = ((tmp_7_fu_659_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp43_fu_703_p2 = ((tmp_8_fu_693_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp46_fu_446_p2 = ((tmp_9_fu_436_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp49_fu_468_p2 = ((tmp_10_fu_458_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_fu_1014_p2 = ((tmp_2_fu_1004_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln390_fu_1154_p2 = ((y_fu_242 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign icmp_ln469_fu_1094_p2 = ((y_1_fu_234 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign icmp_ln501_fu_984_p2 = ((remainPix_fu_971_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln508_fu_1075_p2 = ((y_2_fu_226 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign icmp_ln760_fu_737_p2 = ((y_4_fu_222 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign icmp_ln884_fu_718_p2 = ((y_5_fu_218 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign icmp_ln920_fu_416_p2 = ((remainPix_4_fu_390_p1 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln927_fu_500_p2 = ((y_3_fu_214 == Height_read_reg_1174) ? 1'b1 : 1'b0);

assign mul_ln745_fu_786_p0 = mul_ln745_fu_786_p00;

assign mul_ln745_fu_786_p00 = add_ln745_reg_1344;

assign mul_ln745_fu_786_p1 = 27'd10923;

assign mul_ln868_fu_549_p0 = mul_ln868_fu_549_p00;

assign mul_ln868_fu_549_p00 = add_ln868_reg_1270;

assign mul_ln868_fu_549_p1 = 27'd10923;

assign remainPix_1_fu_990_p3 = ((icmp_ln501_fu_984_p2[0:0] == 1'b1) ? 3'd4 : zext_ln499_fu_980_p1);

assign remainPix_2_fu_808_p3 = ((grp_fu_378_p2[0:0] == 1'b1) ? 4'd8 : zext_ln747_fu_805_p1);

assign remainPix_3_fu_571_p3 = ((grp_fu_378_p2[0:0] == 1'b1) ? 4'd8 : zext_ln870_fu_568_p1);

assign remainPix_4_fu_390_p1 = widthInPix_reg_1195[2:0];

assign remainPix_5_fu_422_p3 = ((icmp_ln920_fu_416_p2[0:0] == 1'b1) ? 4'd8 : zext_ln918_fu_412_p1);

assign remainPix_fu_971_p4 = {{widthInPix_reg_1195[2:1]}};

assign remainTrx_1_fu_623_p3 = ((grp_fu_378_p2[0:0] == 1'b1) ? 3'd3 : trunc_ln7_fu_613_p4);

assign remainTrx_fu_860_p3 = ((grp_fu_378_p2[0:0] == 1'b1) ? 3'd3 : trunc_ln4_fu_850_p4);

assign shl_ln1_fu_579_p3 = {{widthInPix_1_reg_1184}, {5'd0}};

assign shl_ln755_1_fu_827_p3 = {{widthInPix_1_reg_1184}, {3'd0}};

assign shl_ln878_1_fu_590_p3 = {{widthInPix_1_reg_1184}, {3'd0}};

assign shl_ln_fu_816_p3 = {{widthInPix_1_reg_1184}, {5'd0}};

assign sub109_fu_1056_p2 = ($signed(trunc_ln457_1_fu_1040_p4) + $signed(13'd8191));

assign sub200_fu_998_p2 = ($signed(trunc_ln496_1_fu_961_p4) + $signed(13'd8191));

assign sub25_fu_1135_p2 = ($signed(trunc_ln378_1_fu_1119_p4) + $signed(13'd8191));

assign sub336_fu_868_p2 = ($signed(zext_ln745_fu_802_p1) + $signed(12'd4095));

assign sub473_fu_631_p2 = ($signed(zext_ln868_fu_565_p1) + $signed(12'd4095));

assign sub585_fu_430_p2 = ($signed(trunc_ln915_1_fu_402_p4) + $signed(13'd8191));

assign sub_ln755_fu_838_p2 = (zext_ln755_fu_823_p1 - zext_ln755_1_fu_834_p1);

assign sub_ln878_fu_601_p2 = (zext_ln878_fu_586_p1 - zext_ln878_1_fu_597_p1);

assign tmp_10_fu_458_p4 = {{remainPix_5_fu_422_p3[3:2]}};

assign tmp_2_fu_1004_p4 = {{remainPix_1_fu_990_p3[2:1]}};

assign tmp_3_fu_874_p4 = {{remainPix_2_fu_808_p3[3:1]}};

assign tmp_4_fu_896_p4 = {{remainPix_2_fu_808_p3[3:2]}};

assign tmp_5_fu_930_p4 = {{remainTrx_fu_860_p3[2:1]}};

assign tmp_6_fu_637_p4 = {{remainPix_3_fu_571_p3[3:1]}};

assign tmp_7_fu_659_p4 = {{remainPix_3_fu_571_p3[3:2]}};

assign tmp_8_fu_693_p4 = {{remainTrx_1_fu_623_p3[2:1]}};

assign tmp_9_fu_436_p4 = {{remainPix_5_fu_422_p3[3:1]}};

assign trunc_ln2_fu_762_p4 = {{add_ln743_fu_756_p2[15:3]}};

assign trunc_ln378_1_fu_1119_p4 = {{add_ln378_fu_1113_p2[15:3]}};

assign trunc_ln457_1_fu_1040_p4 = {{add_ln457_fu_1034_p2[15:3]}};

assign trunc_ln496_1_fu_961_p4 = {{add_ln496_fu_955_p2[15:3]}};

assign trunc_ln4_fu_850_p4 = {{add_ln755_fu_844_p2[8:6]}};

assign trunc_ln5_fu_525_p4 = {{add_ln866_fu_519_p2[15:3]}};

assign trunc_ln7_fu_613_p4 = {{add_ln878_fu_607_p2[8:6]}};

assign trunc_ln915_1_fu_402_p4 = {{add_ln915_fu_396_p2[15:3]}};

assign xor_ln383_fu_1129_p2 = (grp_fu_383_p3 ^ 1'd1);

assign xor_ln462_fu_1050_p2 = (grp_fu_383_p3 ^ 1'd1);

assign y_11_fu_1080_p2 = (y_2_fu_226 + 12'd1);

assign y_13_fu_742_p2 = (y_4_fu_222 + 12'd1);

assign y_15_fu_723_p2 = (y_5_fu_218 + 12'd1);

assign y_17_fu_505_p2 = (y_3_fu_214 + 12'd1);

assign y_7_fu_1159_p2 = (y_fu_242 + 12'd1);

assign y_9_fu_1099_p2 = (y_1_fu_234 + 12'd1);

assign zext_ln378_fu_1110_p1 = widthInPix_reg_1195;

assign zext_ln457_fu_1031_p1 = widthInPix_reg_1195;

assign zext_ln496_fu_952_p1 = widthInPix_reg_1195;

assign zext_ln499_fu_980_p1 = remainPix_fu_971_p4;

assign zext_ln743_fu_753_p1 = widthInPix_reg_1195;

assign zext_ln745_fu_802_p1 = trunc_ln3_reg_1349;

assign zext_ln747_fu_805_p1 = widthInPix_1_reg_1184;

assign zext_ln755_1_fu_834_p1 = shl_ln755_1_fu_827_p3;

assign zext_ln755_fu_823_p1 = shl_ln_fu_816_p3;

assign zext_ln866_fu_516_p1 = widthInPix_reg_1195;

assign zext_ln868_fu_565_p1 = trunc_ln6_reg_1275;

assign zext_ln870_fu_568_p1 = widthInPix_1_reg_1184;

assign zext_ln878_1_fu_597_p1 = shl_ln878_1_fu_590_p3;

assign zext_ln878_fu_586_p1 = shl_ln1_fu_579_p3;

assign zext_ln915_fu_393_p1 = widthInPix_reg_1195;

assign zext_ln918_fu_412_p1 = remainPix_4_fu_390_p1;

endmodule //design_1_v_frmbuf_wr_0_0_MultiPixStream2Bytes
