# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/validationConstraint.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_audio_formatter_0/design_1_audio_formatter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_audio_formatter_0 || ORIG_REF_NAME==design_1_audio_formatter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_4/design_1_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_4 || ORIG_REF_NAME==design_1_xbar_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_0/design_1_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_0 || ORIG_REF_NAME==design_1_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_receiver_0/design_1_i2s_receiver_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2s_receiver_0 || ORIG_REF_NAME==design_1_i2s_receiver_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2s_transmitter_0/design_1_i2s_transmitter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2s_transmitter_0 || ORIG_REF_NAME==design_1_i2s_transmitter_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_mclk_0/design_1_rst_mclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_mclk_0 || ORIG_REF_NAME==design_1_rst_mclk_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DVI_Transmitter_0_0/design_1_DVI_Transmitter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DVI_Transmitter_0_0 || ORIG_REF_NAME==design_1_DVI_Transmitter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_1/design_1_axi_interconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_1 || ORIG_REF_NAME==design_1_axi_interconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_subset_converter_0_0 || ORIG_REF_NAME==design_1_axis_subset_converter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_dyn_0/design_1_clk_wiz_dyn_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_dyn_0 || ORIG_REF_NAME==design_1_clk_wiz_dyn_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_hdmi_vtc_0/design_1_hdmi_vtc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_hdmi_vtc_0 || ORIG_REF_NAME==design_1_hdmi_vtc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_hdmi_dynclk_0/design_1_rst_hdmi_dynclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_hdmi_dynclk_0 || ORIG_REF_NAME==design_1_rst_hdmi_dynclk_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_1_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_interconnect_0_2/design_1_axi_interconnect_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_interconnect_0_2 || ORIG_REF_NAME==design_1_axi_interconnect_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_153M_0/design_1_rst_ps7_0_153M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_153M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_153M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_proc_ss_0_0/design_1_v_proc_ss_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_proc_ss_0_0 || ORIG_REF_NAME==design_1_v_proc_ss_0_0} -quiet] -quiet

# Block Designs: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b || ORIG_REF_NAME==bd_d92b} -quiet] -quiet

# IP: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_d92b_csc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d92b_csc_0 || ORIG_REF_NAME==bd_d92b_csc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_3/design_1_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_3 || ORIG_REF_NAME==design_1_xlslice_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_2/design_1_xlslice_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_2 || ORIG_REF_NAME==design_1_xlslice_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_v_tpg_0_0 || ORIG_REF_NAME==design_1_v_tpg_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_4/design_1_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_4 || ORIG_REF_NAME==design_1_xlslice_0_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_IIC_HDMI_0/design_1_IIC_HDMI_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_IIC_HDMI_0 || ORIG_REF_NAME==design_1_IIC_HDMI_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_5/design_1_xbar_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_5 || ORIG_REF_NAME==design_1_xbar_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rest_gpio_0/design_1_rest_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rest_gpio_0 || ORIG_REF_NAME==design_1_rest_gpio_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_41/design_1_s00_regslice_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_41 || ORIG_REF_NAME==design_1_s00_regslice_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_41/design_1_s00_data_fifo_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_41 || ORIG_REF_NAME==design_1_s00_data_fifo_41} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_42/design_1_s00_regslice_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_42 || ORIG_REF_NAME==design_1_s00_regslice_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_42/design_1_s00_data_fifo_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_42 || ORIG_REF_NAME==design_1_s00_data_fifo_42} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_audio_formatter_0/design_1_audio_formatter_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_audio_formatter_0 || ORIG_REF_NAME==design_1_audio_formatter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_i2s_receiver_0/design_1_i2s_receiver_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_i2s_receiver_0 || ORIG_REF_NAME==design_1_i2s_receiver_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_i2s_transmitter_0/design_1_i2s_transmitter_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_i2s_transmitter_0 || ORIG_REF_NAME==design_1_i2s_transmitter_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_mclk_0/design_1_rst_mclk_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mclk_0 || ORIG_REF_NAME==design_1_rst_mclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_mclk_0/design_1_rst_mclk_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_mclk_0 || ORIG_REF_NAME==design_1_rst_mclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_axis_subset_converter_0_0/design_1_axis_subset_converter_0_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_dyn_0/design_1_clk_wiz_dyn_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_dyn_0 || ORIG_REF_NAME==design_1_clk_wiz_dyn_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_dyn_0/design_1_clk_wiz_dyn_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_dyn_0 || ORIG_REF_NAME==design_1_clk_wiz_dyn_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_dyn_0/design_1_clk_wiz_dyn_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_hdmi_vtc_0/design_1_hdmi_vtc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_hdmi_vtc_0 || ORIG_REF_NAME==design_1_hdmi_vtc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_hdmi_dynclk_0/design_1_rst_hdmi_dynclk_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_hdmi_dynclk_0 || ORIG_REF_NAME==design_1_rst_hdmi_dynclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_hdmi_dynclk_0/design_1_rst_hdmi_dynclk_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_hdmi_dynclk_0 || ORIG_REF_NAME==design_1_rst_hdmi_dynclk_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_axi4s_vid_out_1_0/design_1_v_axi4s_vid_out_1_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_axi4s_vid_out_1_0 || ORIG_REF_NAME==design_1_v_axi4s_vid_out_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_rd_0_0/design_1_v_frmbuf_rd_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_rd_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_rd_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_153M_0/design_1_rst_ps7_0_153M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_153M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_153M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_153M_0/design_1_rst_ps7_0_153M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_153M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_153M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_frmbuf_wr_0_0/design_1_v_frmbuf_wr_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_frmbuf_wr_0_0 || ORIG_REF_NAME==design_1_v_frmbuf_wr_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/ip/ip_0/bd_d92b_csc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d92b_csc_0 || ORIG_REF_NAME==bd_d92b_csc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_proc_ss_0_0/bd_0/bd_d92b_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_v_tpg_0_0/design_1_v_tpg_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_v_tpg_0_0 || ORIG_REF_NAME==design_1_v_tpg_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_IIC_HDMI_0/design_1_IIC_HDMI_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_IIC_HDMI_0 || ORIG_REF_NAME==design_1_IIC_HDMI_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_IIC_HDMI_0/design_1_IIC_HDMI_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rest_gpio_0/design_1_rest_gpio_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rest_gpio_0 || ORIG_REF_NAME==design_1_rest_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rest_gpio_0/design_1_rest_gpio_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rest_gpio_0/design_1_rest_gpio_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rest_gpio_0 || ORIG_REF_NAME==design_1_rest_gpio_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_us_0/design_1_auto_us_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_us_1/design_1_auto_us_1_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_41/design_1_s00_regslice_41_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_41 || ORIG_REF_NAME==design_1_s00_regslice_41} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_41/design_1_s00_data_fifo_41_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_41 || ORIG_REF_NAME==design_1_s00_data_fifo_41} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_41/design_1_s00_data_fifo_41_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_42/design_1_s00_regslice_42_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_42 || ORIG_REF_NAME==design_1_s00_regslice_42} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_42/design_1_s00_data_fifo_42_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_42 || ORIG_REF_NAME==design_1_s00_data_fifo_42} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_42/design_1_s00_data_fifo_42_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2/design_1_auto_pc_2_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3/design_1_auto_pc_3_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0/design_1_auto_cc_0_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1/design_1_auto_cc_1_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_2/design_1_auto_cc_2_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/ip/design_1_auto_cc_3/design_1_auto_cc_3_ooc.xdc

# XDC: c:/Users/Pie/Documents/Xilinx/CAM_20_V/CAM_20_V/validate_vid_pip/validate_vid_pip.gen/sources_1/bd/design_1/design_1_ooc.xdc
