-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    height : IN STD_LOGIC_VECTOR (15 downto 0);
    width : IN STD_LOGIC_VECTOR (15 downto 0);
    bckgndId : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta : IN STD_LOGIC_VECTOR (15 downto 0);
    dpDynamicRange : IN STD_LOGIC_VECTOR (7 downto 0);
    dpYUVCoef : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (29 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv10_130 : STD_LOGIC_VECTOR (9 downto 0) := "0100110000";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv10_254 : STD_LOGIC_VECTOR (9 downto 0) := "1001010100";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_54 : STD_LOGIC_VECTOR (6 downto 0) := "1010100";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_14 : STD_LOGIC_VECTOR (4 downto 0) := "10100";
    constant ap_const_lv10_1AC : STD_LOGIC_VECTOR (9 downto 0) := "0110101100";
    constant ap_const_lv10_200 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal rampStart : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal ap_block_state1 : BOOLEAN;
    signal cmp2_i224_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp2_i224_reg_1197 : STD_LOGIC_VECTOR (0 downto 0);
    signal conv2_i_i10_i229_fu_624_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_i_i10_i229_reg_1202 : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_i_i_i_cast_cast_fu_632_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i_i_cast_cast_reg_1207 : STD_LOGIC_VECTOR (2 downto 0);
    signal conv2_i_i10_i234_fu_640_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_i_i10_i234_reg_1212 : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_i_i_i236_cast_cast_fu_648_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal conv2_i_i_i236_cast_cast_reg_1217 : STD_LOGIC_VECTOR (6 downto 0);
    signal conv2_i_i10_i252_cast_cast_cast_cast_fu_656_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i10_i252_cast_cast_cast_cast_reg_1222 : STD_LOGIC_VECTOR (4 downto 0);
    signal conv2_i_i_i254_fu_664_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal conv2_i_i_i254_reg_1227 : STD_LOGIC_VECTOR (9 downto 0);
    signal pix_fu_672_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pix_reg_1232 : STD_LOGIC_VECTOR (9 downto 0);
    signal pix_5_fu_680_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal pix_5_reg_1237 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_fu_708_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1242 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1247 : STD_LOGIC_VECTOR (0 downto 0);
    signal barWidth_reg_1252 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_fu_770_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1258 : STD_LOGIC_VECTOR (10 downto 0);
    signal rampStart_load_reg_1263 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_3_reg_1269 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp12_i_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1281 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln518_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_reg_1286 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal colorSel_reg_1291 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln1404_fu_1002_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal trunc_ln1404_reg_1296 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_din : STD_LOGIC_VECTOR (29 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_404_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_400 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_416_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_412 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_428_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_424 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rampVal_3_new_0_fu_318 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_314 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_loc_0_fu_310 : STD_LOGIC_VECTOR (15 downto 0);
    signal hBarSel_4_0_loc_0_fu_306 : STD_LOGIC_VECTOR (7 downto 0);
    signal zonePlateVAddr_loc_0_fu_302 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_loc_0_fu_298 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_0_loc_0_fu_294 : STD_LOGIC_VECTOR (7 downto 0);
    signal hdata_new_0_fu_290 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_286 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_2_loc_0_fu_282 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_3_0_loc_0_fu_278 : STD_LOGIC_VECTOR (7 downto 0);
    signal rampVal_2_new_0_fu_274 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_270 : STD_LOGIC_VECTOR (15 downto 0);
    signal vBarSel_3_loc_0_fu_266 : STD_LOGIC_VECTOR (7 downto 0);
    signal hBarSel_5_0_loc_0_fu_262 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_2_0_0_0467_lcssa476_fu_254 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_1_0_0_0465_lcssa473_fu_250 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_0_0_0_0_0463_lcssa470_fu_246 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln705_fu_946_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal y_fu_258 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln518_fu_925_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln518_fu_848_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1730_fu_840_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1642_fu_828_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1493_fu_812_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1367_fu_804_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1212_fu_788_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_688_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_692_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_698_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_76_fu_714_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_fu_724_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_i_fu_740_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add5_i_fu_718_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_8_fu_756_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_cast_fu_766_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln705_fu_942_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (29 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        pix_5 : IN STD_LOGIC_VECTOR (9 downto 0);
        pix : IN STD_LOGIC_VECTOR (9 downto 0);
        conv2_i_i_i254 : IN STD_LOGIC_VECTOR (9 downto 0);
        conv2_i_i_i236_cast_cast : IN STD_LOGIC_VECTOR (6 downto 0);
        conv2_i_i_i_cast_cast : IN STD_LOGIC_VECTOR (2 downto 0);
        conv2_i_i10_i252_cast_cast_cast_cast : IN STD_LOGIC_VECTOR (4 downto 0);
        conv2_i_i10_i234 : IN STD_LOGIC_VECTOR (9 downto 0);
        conv2_i_i10_i229 : IN STD_LOGIC_VECTOR (9 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (9 downto 0);
        Zplate_Hor_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        bckgndId_load : IN STD_LOGIC_VECTOR (7 downto 0);
        cmp2_i224 : IN STD_LOGIC_VECTOR (0 downto 0);
        zext_ln1032 : IN STD_LOGIC_VECTOR (9 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormatLocal : IN STD_LOGIC_VECTOR (7 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        Zplate_Hor_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        Zplate_Ver_Control_Start : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        Zplate_Ver_Control_Delta : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        loopWidth_cast29 : IN STD_LOGIC_VECTOR (15 downto 0);
        loopHeight_cast24 : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln520 : IN STD_LOGIC_VECTOR (15 downto 0);
        trunc_ln : IN STD_LOGIC_VECTOR (9 downto 0);
        cmp35_i431 : IN STD_LOGIC_VECTOR (0 downto 0);
        fineCourseSel : IN STD_LOGIC_VECTOR (0 downto 0);
        colorSel : IN STD_LOGIC_VECTOR (1 downto 0);
        dpDynamicRange_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dpYUVCoef_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0466_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0466_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_2_0_0_0466_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0464_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0464_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_1_0_0_0464_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0462_out_i : IN STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0462_out_o : OUT STD_LOGIC_VECTOR (9 downto 0);
        p_0_0_0_0_0462_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (9 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_ap_vld : OUT STD_LOGIC;
        s : IN STD_LOGIC_VECTOR (31 downto 0);
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_0_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_0_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_5_0_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_520_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_400,
        hdata_flag_0 => hdata_flag_0_reg_412,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_424,
        loopWidth => width,
        pix_5 => pix_5_reg_1237,
        pix => pix_reg_1232,
        conv2_i_i_i254 => conv2_i_i_i254_reg_1227,
        conv2_i_i_i236_cast_cast => conv2_i_i_i236_cast_cast_reg_1217,
        conv2_i_i_i_cast_cast => conv2_i_i_i_cast_cast_reg_1207,
        conv2_i_i10_i252_cast_cast_cast_cast => conv2_i_i10_i252_cast_cast_cast_cast_reg_1222,
        conv2_i_i10_i234 => conv2_i_i10_i234_reg_1212,
        conv2_i_i10_i229 => conv2_i_i10_i229_reg_1202,
        rampStart_1 => rampStart_load_reg_1263,
        Zplate_Hor_Control_Start => ZplateHorContStart,
        bckgndId_load => bckgndId,
        cmp2_i224 => cmp2_i224_reg_1197,
        zext_ln1032 => rampStart_load_reg_1263,
        y => y_3_reg_1269,
        colorFormatLocal => colorFormat,
        barWidth_cast => barWidth_reg_1252,
        barWidth => barWidth_reg_1252,
        Zplate_Hor_Control_Delta => ZplateHorContDelta,
        Zplate_Ver_Control_Start => ZplateVerContStart,
        cmp12_i => cmp12_i_reg_1281,
        Zplate_Ver_Control_Delta => ZplateVerContDelta,
        sub_i_i_i => sub_i_i_i_reg_1258,
        barWidthMinSamples => barWidthMinSamples_reg_1242,
        loopWidth_cast29 => width,
        loopHeight_cast24 => height,
        zext_ln520 => y_3_reg_1269,
        trunc_ln => trunc_ln1404_reg_1296,
        cmp35_i431 => icmp_reg_1247,
        fineCourseSel => tmp_33_reg_1286,
        colorSel => colorSel_reg_1291,
        dpDynamicRange_1 => dpDynamicRange,
        dpYUVCoef_1 => dpYUVCoef,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_314,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_310,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_0_loc_1_out_i => hBarSel_4_0_loc_0_fu_306,
        hBarSel_4_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o,
        hBarSel_4_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_302,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_298,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_0_loc_1_out_i => hBarSel_0_loc_0_fu_294,
        hBarSel_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o,
        hBarSel_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_286,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_282,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_0_loc_1_out_i => hBarSel_3_0_loc_0_fu_278,
        hBarSel_3_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o,
        hBarSel_3_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_270,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_266,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_0_loc_1_out_i => hBarSel_5_0_loc_0_fu_262,
        hBarSel_5_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o,
        hBarSel_5_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o_ap_vld,
        p_0_2_0_0_0466_out_i => p_0_2_0_0_0467_lcssa476_fu_254,
        p_0_2_0_0_0466_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o,
        p_0_2_0_0_0466_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o_ap_vld,
        p_0_1_0_0_0464_out_i => p_0_1_0_0_0465_lcssa473_fu_250,
        p_0_1_0_0_0464_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o,
        p_0_1_0_0_0464_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o_ap_vld,
        p_0_0_0_0_0462_out_i => p_0_0_0_0_0463_lcssa470_fu_246,
        p_0_0_0_0_0462_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o,
        p_0_0_0_0_0462_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_ap_vld,
        hBarSel_4_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0,
        hBarSel_4_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_ap_vld,
        s => s,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_ap_vld,
        hBarSel_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0,
        hBarSel_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_ap_vld,
        hBarSel_3_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0,
        hBarSel_3_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_ap_vld,
        hBarSel_5_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0,
        hBarSel_5_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_0_loc_0_fu_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_0_loc_0_fu_294 <= zext_ln1493_fu_812_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_0_loc_0_fu_294 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_3_0_loc_0_fu_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_3_0_loc_0_fu_278 <= zext_ln1642_fu_828_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_3_0_loc_0_fu_278 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_0_loc_0_fu_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_0_loc_0_fu_306 <= hBarSel_4_0;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_4_0_loc_0_fu_306 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_0_loc_0_fu_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_5_0_loc_0_fu_262 <= zext_ln518_fu_848_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_5_0_loc_0_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_412_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                hdata_flag_0_reg_412 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_412 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_286_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_286 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hdata_loc_0_fu_286 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_2_flag_0_reg_424 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_424 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_270 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_2_loc_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_400_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_3_flag_0_reg_400 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_flag_1_out;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_400 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_314 <= rampVal_1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_3_loc_0_fu_314 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_310_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_310 <= zext_ln1212_fu_788_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_loc_0_fu_310 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_282_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_2_loc_0_fu_282 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_2_loc_0_fu_282 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_3_loc_0_fu_266 <= zext_ln1730_fu_840_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_3_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_298_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_loc_0_fu_298 <= zext_ln1367_fu_804_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_loc_0_fu_298 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_258 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_0))) then 
                y_fu_258 <= add_ln518_fu_925_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_302_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_302 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                zonePlateVAddr_loc_0_fu_302 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                barWidthMinSamples_reg_1242 <= barWidthMinSamples_fu_708_p2;
                barWidth_reg_1252 <= add_i_fu_740_p2(13 downto 3);
                cmp2_i224_reg_1197 <= cmp2_i224_fu_618_p2;
                    conv2_i_i10_i229_reg_1202(3 downto 0) <= conv2_i_i10_i229_fu_624_p3(3 downto 0);    conv2_i_i10_i229_reg_1202(7 downto 6) <= conv2_i_i10_i229_fu_624_p3(7 downto 6);    conv2_i_i10_i229_reg_1202(9) <= conv2_i_i10_i229_fu_624_p3(9);
                    conv2_i_i10_i234_reg_1212(2) <= conv2_i_i10_i234_fu_640_p3(2);    conv2_i_i10_i234_reg_1212(4) <= conv2_i_i10_i234_fu_640_p3(4);    conv2_i_i10_i234_reg_1212(6) <= conv2_i_i10_i234_fu_640_p3(6);    conv2_i_i10_i234_reg_1212(9) <= conv2_i_i10_i234_fu_640_p3(9);
                    conv2_i_i10_i252_cast_cast_cast_cast_reg_1222(2) <= conv2_i_i10_i252_cast_cast_cast_cast_fu_656_p3(2);    conv2_i_i10_i252_cast_cast_cast_cast_reg_1222(4) <= conv2_i_i10_i252_cast_cast_cast_cast_fu_656_p3(4);
                    conv2_i_i_i236_cast_cast_reg_1217(2) <= conv2_i_i_i236_cast_cast_fu_648_p3(2);    conv2_i_i_i236_cast_cast_reg_1217(4) <= conv2_i_i_i236_cast_cast_fu_648_p3(4);    conv2_i_i_i236_cast_cast_reg_1217(6) <= conv2_i_i_i236_cast_cast_fu_648_p3(6);
                    conv2_i_i_i254_reg_1227(1 downto 0) <= conv2_i_i_i254_fu_664_p3(1 downto 0);    conv2_i_i_i254_reg_1227(4) <= conv2_i_i_i254_fu_664_p3(4);    conv2_i_i_i254_reg_1227(6) <= conv2_i_i_i254_fu_664_p3(6);    conv2_i_i_i254_reg_1227(9) <= conv2_i_i_i254_fu_664_p3(9);
                    conv2_i_i_i_cast_cast_reg_1207(2) <= conv2_i_i_i_cast_cast_fu_632_p3(2);
                icmp_reg_1247 <= icmp_fu_734_p2;
                    pix_5_reg_1237(8 downto 0) <= pix_5_fu_680_p3(8 downto 0);
                    pix_reg_1232(9) <= pix_fu_672_p3(9);
                rampStart_load_reg_1263 <= rampStart;
                sub_i_i_i_reg_1258 <= sub_i_i_i_fu_770_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_0))) then
                cmp12_i_reg_1281 <= cmp12_i_fu_931_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                colorSel_reg_1291 <= y_3_reg_1269(7 downto 6);
                tmp_33_reg_1286 <= y_3_reg_1269(5 downto 5);
                trunc_ln1404_reg_1296 <= trunc_ln1404_fu_1002_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hBarSel_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_hdata_flag_0_phi_fu_416_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then
                hdata <= hdata_new_0_fu_290;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hdata_new_0_fu_290 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_0463_lcssa470_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_0_0_0_0462_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_0465_lcssa473_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_1_0_0_0464_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_0467_lcssa476_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_p_0_2_0_0_0466_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then
                rampStart <= add_ln705_fu_946_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_3_flag_0_phi_fu_404_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then
                rampVal_1 <= rampVal_3_new_0_fu_318;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_phi_mux_rampVal_2_flag_0_phi_fu_428_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then
                rampVal_2 <= rampVal_2_new_0_fu_274;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_2_new_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_3_new_0_fu_318 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                y_3_reg_1269 <= y_fu_258;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_zonePlateVAddr;
            end if;
        end if;
    end process;
    conv2_i_i10_i229_reg_1202(5 downto 4) <= "11";
    conv2_i_i10_i229_reg_1202(8) <= '1';
    conv2_i_i_i_cast_cast_reg_1207(1 downto 0) <= "00";
    conv2_i_i10_i234_reg_1212(1 downto 0) <= "00";
    conv2_i_i10_i234_reg_1212(3 downto 3) <= "0";
    conv2_i_i10_i234_reg_1212(5 downto 5) <= "0";
    conv2_i_i10_i234_reg_1212(8 downto 7) <= "00";
    conv2_i_i_i236_cast_cast_reg_1217(1 downto 0) <= "00";
    conv2_i_i_i236_cast_cast_reg_1217(3 downto 3) <= "0";
    conv2_i_i_i236_cast_cast_reg_1217(5) <= '0';
    conv2_i_i10_i252_cast_cast_cast_cast_reg_1222(1 downto 0) <= "00";
    conv2_i_i10_i252_cast_cast_cast_cast_reg_1222(3) <= '0';
    conv2_i_i_i254_reg_1227(3 downto 2) <= "11";
    conv2_i_i_i254_reg_1227(5 downto 5) <= "1";
    conv2_i_i_i254_reg_1227(8 downto 7) <= "11";
    pix_reg_1232(8 downto 0) <= "000000000";
    pix_5_reg_1237(9) <= '1';

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln518_fu_920_p2, grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add2_i_fu_692_p2 <= std_logic_vector(unsigned(empty_fu_688_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_718_p2 <= std_logic_vector(unsigned(empty_76_fu_714_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_740_p2 <= std_logic_vector(unsigned(empty_fu_688_p1) + unsigned(ap_const_lv14_7));
    add_ln518_fu_925_p2 <= std_logic_vector(unsigned(y_fu_258) + unsigned(ap_const_lv16_1));
    add_ln705_fu_946_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(zext_ln705_fu_942_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(real_start, ap_done_reg)
    begin
        if (((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln518_fu_920_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_416_p4 <= hdata_flag_0_reg_412;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_428_p4 <= rampVal_2_flag_0_reg_424;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_404_p4 <= rampVal_3_flag_0_reg_400;
    ap_ready <= internal_ap_ready;
    barHeight_cast_cast_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_756_p4),11));
    barWidthMinSamples_fu_708_p2 <= std_logic_vector(unsigned(p_cast_fu_698_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp12_i_fu_931_p2 <= "0" when (y_fu_258 = ap_const_lv16_0) else "1";
    cmp2_i224_fu_618_p2 <= "1" when (colorFormat = ap_const_lv8_0) else "0";
    conv2_i_i10_i229_fu_624_p3 <= 
        ap_const_lv10_3FF when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv10_130;
    conv2_i_i10_i234_fu_640_p3 <= 
        ap_const_lv10_0 when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv10_254;
    conv2_i_i10_i252_cast_cast_cast_cast_fu_656_p3 <= 
        ap_const_lv5_0 when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv5_14;
    conv2_i_i_i236_cast_cast_fu_648_p3 <= 
        ap_const_lv7_0 when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv7_54;
    conv2_i_i_i254_fu_664_p3 <= 
        ap_const_lv10_3FF when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv10_1AC;
    conv2_i_i_i_cast_cast_fu_632_p3 <= 
        ap_const_lv3_0 when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv3_4;
    empty_76_fu_714_p1 <= height(14 - 1 downto 0);
    empty_fu_688_p1 <= width(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_520_2_fu_436_ap_start_reg;
    icmp_fu_734_p2 <= "0" when (tmp_fu_724_p4 = ap_const_lv7_0) else "1";
    icmp_ln518_fu_920_p2 <= "1" when (y_fu_258 = height) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln518_fu_920_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln518_fu_920_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    p_cast_fu_698_p4 <= add2_i_fu_692_p2(13 downto 4);
    pix_5_fu_680_p3 <= 
        ap_const_lv10_3FF when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv10_200;
    pix_fu_672_p3 <= 
        ap_const_lv10_0 when (cmp2_i224_fu_618_p2(0) = '1') else 
        ap_const_lv10_200;

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    sub_i_i_i_fu_770_p2 <= std_logic_vector(unsigned(barHeight_cast_cast_fu_766_p1) + unsigned(ap_const_lv11_7FF));
    tmp_8_fu_756_p4 <= add5_i_fu_718_p2(13 downto 4);
    tmp_fu_724_p4 <= colorFormat(7 downto 1);
    trunc_ln1404_fu_1002_p1 <= y_3_reg_1269(10 - 1 downto 0);
    zext_ln1212_fu_788_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1367_fu_804_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1493_fu_812_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_0),8));
    zext_ln1642_fu_828_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3_0),8));
    zext_ln1730_fu_840_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln518_fu_848_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_5_0),8));
    zext_ln705_fu_942_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(motionSpeed),10));
end behav;
